### PR TITLE
Use contextual dispatch for device functions.

### LINKED ISSUE #42: Add support for `sincos`, `cis`?
I have two related questions/comments:
### First question
I was looking into adding CUDAnative support for [`cis`](https://docs.julialang.org/en/latest/base/math/#Base.cis). This can be done by essentially copying the Base code with a few `@cufunc`s in front. In the case of `Real` arguments, this works:
```julia
@cufunc sincos(theta::Real) = sin(theta), cos(theta) #See also next question...

@cufunc function cis(theta::Real)
    s, c = sincos(theta)
    Complex(c, s)
end
```
In CUDAnative I guess one would just have to add these functions to `src/device/cuda/math.jl`. However, this raises the first question: Which functions do you ultimately intend to include in CUDAnative? Should these functions be included, or just functions limited to those natively implemented in CUDA? (With a few exceptions, I've noted...) I mean, it's maybe not so elegant to copy a large portion of Base into CUDAnative. On the other hand, nor is it elegant to include the above in my own code whenever it's needed...

### Second question
While looking into this, I realized that [CUDA has a native `sincos`](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html#group__CUDA__MATH__SINGLE_1g9456ff9df91a3874180d89a94b36fd46) which maybe is more "worthy" of being included in CUDAnative (?). However, I'm not quite sure how to do this myself based on what's already written in `src/device/cuda/math.jl`, given that the CUDA implementation is calculated in place (returned by reference). What's the recommended way of doing this in cases like these?

### LINKED ISSUE #60: Accidentally calling GPU intrinsics on the host causes segfaults
```
CUDA_VISIBLE_DEVICES=3 julia --project=..
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.3 (2018-12-18)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using CUDAnative

julia> f(x) = CUDAnative.tanh(x)
f (generic function with 1 method)

julia> @code_typed f(1f0)
CodeInfo(
1 1 ─ %1 = Base.llvmcall::IntrinsicFunction                                                                                              │╻╷ tanh
  │   %2 = (%1)(("declare float @__nv_tanhf(float)", "%2 =  call float @__nv_tanhf(float %0)\nret float %2"), Float32, Tuple{Float32}, x)::Float32o expansion
  └──      return %2                                                                                                                     │
) => Float32

julia> f(1f0)

signal (11): Segmentation fault
in expression starting at no file:0
_ITM_registerTMCloneTable at /opt/julia/julia-1.0.3/bin/../lib/julia/libspqr.so (unknown line)
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2184
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:82
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:117 [inlined]
JuliaGPU/CUDAnative.jl#28 at ./task.jl:259
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2184
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1537 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:268
unknown function (ip: 0xffffffffffffffff)
Allocations: 4184659 (Pool: 4183753; Big: 906); GC: 8
Segmentation fault (core dumped)
```
My suggestion would be to
1. Switch this to ccall with llvmcall calling convention
2. Add an llvmcall_gpu calling convention that emits an error when somebody tries to compile it for a host backend.

cc @maleadt

### LINKED ISSUE #71: Cannot select `fpow` while lowering `pow.f32`
```julia
julia> using CUDAdrv, CUDAnative

julia> a = round.(rand(Float32, (3, 4)) * 100)
3×4 Array{Float32,2}:
 57.0  13.0  55.0  14.0
 78.0  55.0  90.0  73.0
 61.0  85.0  36.0  85.0

julia> d_a = CuArray(a)
3×4 Array{Float32,2}:
 57.0  13.0  55.0  14.0
 78.0  55.0  90.0  73.0
 61.0  85.0  36.0  85.0

julia> d_b = similar(d_a)
3×4 Array{Float32,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

julia> function kernel_vpow(a, b)
           i = (blockIdx().x-1) * blockDim().x + threadIdx().x
           b[i] = a[i]^1.5
           return nothing
       end
kernel_vpow (generic function with 1 method)

julia> @cuda (3,4) kernel_vpow(d_a, d_b)
ERROR: LLVM error: Cannot select: 0x6092650: f64 = fpow 0x6092570, ConstantFP:f64<1.500000e+00>
  0x6092570: f64 = fp_extend 0x6092180
    0x6092180: f32,ch = load<LD4[null(addrspace=101)]> 0x447c450, TargetExternalSymbol:i64'julia_^_61355_param_0', undef:i64
      0x60920a0: i64 = TargetExternalSymbol'julia_^_61355_param_0'
      0x6092110: i64 = undef
  0x60925e0: f64 = ConstantFP<1.500000e+00>
In function: julia_^_61355
Stacktrace:
 [1] handle_error(::Cstring) at /home/alha02/.julia/v0.6/LLVM/src/core/context.jl:96
 [2] macro expansion at /home/alha02/.julia/v0.6/LLVM/src/util/logging.jl:102 [inlined]
 [3] macro expansion at /home/alha02/.julia/v0.6/LLVM/src/base.jl:18 [inlined]
 [4] LLVMTargetMachineEmitToMemoryBuffer(::Ptr{LLVM.API.LLVMOpaqueTargetMachine}, ::Ptr{LLVM.API.LLVMOpaqueModule}, ::UInt32, ::Base.RefValue{Cstring}, ::Base.RefValue{Ptr{LLVM.API.LLVMOpaqueMemoryBuffer}}) at /home/alha02/.julia/v0.6/LLVM/src/../lib/3.9/libLLVM_h.jl:301
 [5] emit(::LLVM.TargetMachine, ::LLVM.Module, ::UInt32) at /home/alha02/.julia/v0.6/LLVM/src/targetmachine.jl:39
 [6] #mcgen#45(::Bool, ::Function, ::LLVM.Module, ::LLVM.Function, ::VersionNumber) at /home/alha02/.julia/v0.6/CUDAnative/src/jit.jl:303
 [7] (::CUDAnative.#kw##mcgen)(::Array{Any,1}, ::CUDAnative.#mcgen, ::LLVM.Module, ::LLVM.Function, ::VersionNumber) at ./<missing>:0
 [8] #compile_function#46(::Bool, ::Function, ::Any, ::Any, ::VersionNumber) at /home/alha02/.julia/v0.6/CUDAnative/src/jit.jl:328
 [9] cufunction(::CUDAdrv.CuDevice, ::Any, ::Any) at /home/alha02/.julia/v0.6/CUDAnative/src/jit.jl:369
 [10] macro expansion at /home/alha02/.julia/v0.6/CUDAnative/src/execution.jl:107 [inlined]
 [11] _cuda(::Tuple{Int64,Int64}, ::Int64, ::CUDAdrv.CuStream, ::#kernel_vpow, ::CUDAnative.CuDeviceArray{Float32,2,CUDAnative.AS.Global}, ::CUDAnative.CuDeviceArray{Float32,2,CUDAnative.AS.Global}) at /home/alha02/.julia/v0.6/CUDAnative/src/execution.jl:80
```
Integer powers are no problem:
```julia
julia> function kernel_vpow(a, b)
           i = (blockIdx().x-1) * blockDim().x + threadIdx().x
           b[i] = a[i]^2
           return nothing
       end
kernel_vpow (generic function with 1 method)

julia> @cuda (3,4) kernel_vpow(d_a, d_b)

julia> d_b
3×4 Array{Float32,2}:
 3249.0   169.0  3025.0   196.0
 6084.0  3025.0  8100.0  5329.0
 3721.0  7225.0  1296.0  7225.0
```

### LINKED ISSUE #76: Cannot select `__powidf2` while lowering `powi.f64`
Repro:

``` julia
@target ptx function foo(n)
    return 1.0^n
end
code_native(foo, Tuple{Int})
```

Generated IR:

``` llvm
define double @julia_foo_64487(i64) #0 !dbg !6 {
top:
  %sext = shl i64 %0, 32
  %1 = ashr exact i64 %sext, 32
  %2 = icmp eq i64 %1, %0
  br i1 %2, label %pass, label %fail

fail:                                             ; preds = %top
  call void @llvm.trap() JuliaGPU/CUDAnative.jl#2
  unreachable

pass:                                             ; preds = %top
  %3 = trunc i64 %0 to i32
  %4 = call double @llvm.powi.f64(double 1.000000e+00, i32 %3)
  ret double %4
}

```

`versioninfo()`:

```
Julia Version 0.6.0-dev.884
Commit 34d11b0* (2016-09-14 21:55 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.0 (ORCJIT, ivybridge)
```

### LINKED ISSUE #130: Bug involving broadcasting, sqrt, and Flux
**Describe the bug**
Running some moderately complicated code using CuArrays and Flux TrackedArrays, fails, typically crashing silently.

**To Reproduce**
The Minimal Working Example (MWE) for this bug (as minimal as I could make it):
```julia
using CuArrays
using Flux

struct LearnedStdModel{C, T}
    chain::C
    std::T
end

Flux.@treelike LearnedStdModel

function LearnedStdModel(layers...; init_factor=1.0f0)
    LearnedStdModel(
        Chain(layers...),
        param([init_factor])
    )
end

(mdl::LearnedStdModel)(xs) = (mdl.chain(xs), mdl.std)

function logprob(m, s, x)
    -(((x .- m).^2) ./ (2.0f0 .* s.^2)) .- sqrt.(6.28318f0 .* s.^2)
end

function action_mwe(model::LearnedStdModel, state)
    m, s = model(state)
    action = cu([1.0])
    lp = logprob(m, s, action)
end

model = LearnedStdModel( Dense(4, 128, relu), Dropout(0.2), Dense(128, 1)) |> gpu
s = cu(rand(4))
action_mwe(model, s)
```

**Expected behavior**
A log probability to be computed, outputing a 1-element tracked CuArray.

**Build log**
```
  Building CUDAdrv ───→ `~/.julia/packages/CUDAdrv/WVU1H/deps/build.log`
  Building LLVM ──────→ `~/.julia/packages/LLVM/tg8MX/deps/build.log`
  Building CUDAnative → `~/.julia/packages/CUDAnative/9rZcJ/deps/build.log`
  Building Conda ─────→ `~/.julia/packages/Conda/CpuvI/deps/build.log`
  Building FFTW ──────→ `~/.julia/packages/FFTW/p7sLQ/deps/build.log`
  Building CuArrays ──→ `~/.julia/packages/CuArrays/PwSdF/deps/build.log`

```

**Environment details (please complete this section)**
Details on Julia:
```
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

```

```
Julia packages:
  [c52e3926] Atom v0.8.5
  [da1fd8a2] CodeTracking v0.5.7
  [3a865a2d] CuArrays v1.0.2
  [0c46a032] DifferentialEquations v6.4.0
  [31c24e10] Distributions v0.20.0
  [587475ba] Flux v0.8.3
  [b38be410] FreeType v2.1.1
  [4c0ca9eb] Gtk v0.17.0
  [56b9baea] Gym v0.1.0 #master (https://github.com/FluxML/Gym.jl)
  [e5e0dc1b] Juno v0.7.0
  [ee78f7c6] Makie v0.9.3
  [91a5bcdd] Plots v0.25.1
  [92933f4c] ProgressMeter v0.9.0
  [295af30f] Revise v2.1.5

CUDA: toolkit and driver version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

**Additional context**
Removing `sqrt` from the `logprob` function results in everything working fine.

### LINKED ISSUE #140: Partial support for Dual Numbers
**Describe the bug**
The support for DualNumbers from DualNumbers.jl is partial. I am able to use the base arithmetics (+,*,/) but not any analytic function (exp,sin,cos etc.)

**To Reproduce**
The Minimal Working Example (MWE) for this bug:
```julia
using DualNumbers,CuArrays
p=cuzeros(Dual128,6)
t=exp.(p)
```

### LINKED ISSUE #169: support for vecnorm
I got following error while executing `sum(vecnorm, params(model))`, where model is a Flux Chain.
```
ERROR: LLVM error: Cannot select: 0x559dd22e8a80: f32 = fpow 0x559dd22e91f0, 0x559dd22e8930
  0x559dd22e91f0: f32 = bitcast 0x559dd22e9180
    0x559dd22e9180: i32 = and 0x559dd1bea130, Constant:i32<2147483647>
      0x559dd1bea130: i32,ch = load<LD4[%4]> 0x559dd206c280, 0x559dd1be9870, undef:i64
        0x559dd1be9870: i64,ch = load<LD8[null(addrspace=101)]> 0x559dd206c280, TargetExternalSymbol:i64'julia__26_64205_param_1', undef:i64
          0x559dd1be9800: i64 = TargetExternalSymbol'julia__26_64205_param_1'
          0x559dd1be9720: i64 = undef
        0x559dd1be9720: i64 = undef
      0x559dd22e8460: i32 = Constant<2147483647>
  0x559dd22e8930: f32 = sint_to_fp 0x559dd1be9950
    0x559dd1be9950: i64,ch = load<LD8[null(addrspace=101)]> 0x559dd206c280, TargetExternalSymbol:i64'julia__26_64205_param_2', undef:i64
      0x559dd1be98e0: i64 = TargetExternalSymbol'julia__26_64205_param_2'
      0x559dd1be9720: i64 = undef
In function: julia__26_64205
Stacktrace:
 [1] handle_error(::Cstring) at /home/tejank10/.julia/v0.6/LLVM/src/core/context.jl:100
 [2] macro expansion at /home/tejank10/.julia/v0.6/LLVM/src/base.jl:22 [inlined]
 [3] LLVMTargetMachineEmitToMemoryBuffer(::Ptr{LLVM.API.LLVMOpaqueTargetMachine}, ::Ptr{LLVM.API.LLVMOpaqueModule}, ::UInt32, ::Base.RefValue{Cstring}, ::Base.RefValue{Ptr{LLVM.API.LLVMOpaqueMemoryBuffer}}) at /home/tejank10/.julia/v0.6/LLVM/src/../lib/3.9/libLLVM_h.jl:301
 [4] emit(::LLVM.TargetMachine, ::LLVM.Module, ::UInt32) at /home/tejank10/.julia/v0.6/LLVM/src/targetmachine.jl:42
 [5] #mcgen#57(::Bool, ::Function, ::LLVM.Module, ::LLVM.Function, ::VersionNumber) at /home/tejank10/.julia/v0.6/CUDAnative/src/jit.jl:393
 [6] (::CUDAnative.#kw##mcgen)(::Array{Any,1}, ::CUDAnative.#mcgen, ::LLVM.Module, ::LLVM.Function, ::VersionNumber) at ./<missing>:0
 [7] #compile_function#58(::Bool, ::Function, ::Any, ::Any, ::VersionNumber) at /home/tejank10/.julia/v0.6/CUDAnative/src/jit.jl:440
 [8] cufunction(::CUDAdrv.CuDevice, ::Any, ::Any) at /home/tejank10/.julia/v0.6/CUDAnative/src/jit.jl:488
 [9] macro expansion at /home/tejank10/.julia/v0.6/CUDAnative/src/execution.jl:107 [inlined]
 [10] _cuda(::Tuple{Int64,Int64}, ::Int64, ::CUDAdrv.CuStream, ::CuArrays.#broadcast_kernel, ::Flux.Tracker.##26#27, ::CUDAnative.CuDeviceArray{ForwardDiff.Dual{Void,Float32,3},2,CUDAnative.AS.Global}, ::Tuple{Tuple{Bool,Bool},Tuple{},Tuple{}}, ::Tuple{Tuple{Int64,Int64},Tuple{},Tuple{}}, ::CUDAnative.CuDeviceArray{ForwardDiff.Dual{Void,Float32,3},2,CUDAnative.AS.Global}, ::Tuple{Int64,Float32}) at /home/tejank10/.julia/v0.6/CUDAnative/src/execution.jl:80
 [11] _broadcast! at /home/tejank10/.julia/v0.6/CuArrays/src/broadcast.jl:22 [inlined]
 [12] broadcast_t at /home/tejank10/.julia/v0.6/CuArrays/src/broadcast.jl:37 [inlined]
 [13] broadcast_c at /home/tejank10/.julia/v0.6/CuArrays/src/broadcast.jl:58 [inlined]
 [14] broadcast at ./broadcast.jl:455 [inlined]
 [15] tracked_broadcast(::Function, ::TrackedArray{…,CuArray{Float32,2}}, ::Int64, ::Float32) at /home/tejank10/.julia/v0.6/Flux/src/tracker/array.jl:364
 [16] vecnorm(::TrackedArray{…,CuArray{Float32,2}}, ::Int64) at /home/tejank10/.julia/v0.6/Flux/src/tracker/array.jl:224 (repeats 2 times)
 [17] _mapreduce(::Base.LinAlg.#vecnorm, ::Base.#+, ::IndexLinear, ::Array{Any,1}) at ./reduce.jl:273
 [18] sum(::Function, ::Array{Any,1}) at ./reduce.jl:347
```
The statement works fine while running on CPU

### LINKED ISSUE #171: Any chance x^.a, for (a> 2.0) will be supported at some point?
Very simple `x2 .^ 4` completely fails and has been since the age of times. Any chance this may be supported at some point? It feels like `CuArrays` is in real shortage of TLC. Just my sad perspective of trying to use it, apologies.

```julia
julia> x = rand(Float32, 100);

julia> using Flux

using CuArrays

julia> 

julia> using CuArrays
x2 = x |> gpu;

julia> x2 = x |> gpu;

julia> x2 .^ 4

ERROR: LLVM error: Cannot select: 0x23701520: f32 = fpow 0x237010c0, ConstantFP:f32<4.000000e+00>
  0x237010c0: f32,ch = load<LD4[null(addrspace=101)]> 0x237065b0, TargetExternalSymbol:i64'julia__1_63502_param_0', undef:i64
    0x23700fe0: i64 = TargetExternalSymbol'julia__1_63502_param_0'
    0x23701050: i64 = undef
  0x237014b0: f32 = ConstantFP<4.000000e+00>
In function: julia__1_63502
Stacktrace:
 [1] handle_error(::Cstring) at /home/ubuntu/.julia/v0.6/LLVM/src/core/context.jl:100
 [2] macro expansion at /home/ubuntu/.julia/v0.6/LLVM/src/base.jl:22 [inlined]
 [3] LLVMTargetMachineEmitToMemoryBuffer(::Ptr{LLVM.API.LLVMOpaqueTargetMachine}, ::Ptr{LLVM.API.LLVMOpaqueModule}, ::UInt32, ::Base.RefValue{Cstring}, ::Base.RefValue{Ptr{LLVM.API.LLVMOpaqueMemoryBuffer}}) at /home/ubuntu/.julia/v0.6/LLVM/src/../lib/3.9/libLLVM_h.jl:301
 [4] emit(::LLVM.TargetMachine, ::LLVM.Module, ::UInt32) at /home/ubuntu/.julia/v0.6/LLVM/src/targetmachine.jl:42
 [5] #mcgen#57(::Bool, ::Function, ::LLVM.Module, ::LLVM.Function, ::VersionNumber) at /home/ubuntu/.julia/v0.6/CUDAnative/src/jit.jl:393
 [6] (::CUDAnative.#kw##mcgen)(::Array{Any,1}, ::CUDAnative.#mcgen, ::LLVM.Module, ::LLVM.Function, ::VersionNumber) at ./<missing>:0
 [7] #compile_function#58(::Bool, ::Function, ::Any, ::Any, ::VersionNumber) at /home/ubuntu/.julia/v0.6/CUDAnative/src/jit.jl:440
 [8] cufunction(::CUDAdrv.CuDevice, ::Any, ::Any) at /home/ubuntu/.julia/v0.6/CUDAnative/src/jit.jl:488
 [9] macro expansion at /home/ubuntu/.julia/v0.6/CUDAnative/src/execution.jl:107 [inlined]
 [10] _cuda(::Tuple{Int64,Int64}, ::Int64, ::CUDAdrv.CuStream, ::CuArrays.#broadcast_kernel, ::##1#2, ::CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, ::Tuple{Tuple{Bool}}, ::Tuple{Tuple{Int64}}, ::CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, ::Tuple{}) at /home/ubuntu/.julia/v0.6/CUDAnative/src/execution.jl:80
 [11] _broadcast! at /home/ubuntu/.julia/v0.6/CuArrays/src/broadcast.jl:22 [inlined]
 [12] broadcast_t at /home/ubuntu/.julia/v0.6/CuArrays/src/broadcast.jl:37 [inlined]
 [13] broadcast_c at /home/ubuntu/.julia/v0.6/CuArrays/src/broadcast.jl:58 [inlined]
 [14] broadcast(::Function, ::CuArray{Float32,1}) at ./broadcast.jl:455

julia> 

julia> x2 .^ 4.0
ERROR: LLVM error: Cannot select: 0x252443c0: f64 = fpow 0x252442e0, ConstantFP:f64<4.000000e+00>
  0x252442e0: f64 = fp_extend 0x25243ef0
    0x25243ef0: f32,ch = load<LD4[null(addrspace=101)]> 0x23494000, TargetExternalSymbol:i64'julia_^_63768_param_0', undef:i64
      0x25243e10: i64 = TargetExternalSymbol'julia_^_63768_param_0'
      0x25243e80: i64 = undef
  0x25244350: f64 = ConstantFP<4.000000e+00>
In function: julia_^_63768
Stacktrace:
 [1] handle_error(::Cstring) at /home/ubuntu/.julia/v0.6/LLVM/src/core/context.jl:100
 [2] macro expansion at /home/ubuntu/.julia/v0.6/LLVM/src/base.jl:22 [inlined]
 [3] LLVMTargetMachineEmitToMemoryBuffer(::Ptr{LLVM.API.LLVMOpaqueTargetMachine}, ::Ptr{LLVM.API.LLVMOpaqueModule}, ::UInt32, ::Base.RefValue{Cstring}, ::Base.RefValue{Ptr{LLVM.API.LLVMOpaqueMemoryBuffer}}) at /home/ubuntu/.julia/v0.6/LLVM/src/../lib/3.9/libLLVM_h.jl:301
 [4] emit(::LLVM.TargetMachine, ::LLVM.Module, ::UInt32) at /home/ubuntu/.julia/v0.6/LLVM/src/targetmachine.jl:42
 [5] #mcgen#57(::Bool, ::Function, ::LLVM.Module, ::LLVM.Function, ::VersionNumber) at /home/ubuntu/.julia/v0.6/CUDAnative/src/jit.jl:393
 [6] (::CUDAnative.#kw##mcgen)(::Array{Any,1}, ::CUDAnative.#mcgen, ::LLVM.Module, ::LLVM.Function, ::VersionNumber) at ./<missing>:0
 [7] #compile_function#58(::Bool, ::Function, ::Any, ::Any, ::VersionNumber) at /home/ubuntu/.julia/v0.6/CUDAnative/src/jit.jl:440
 [8] cufunction(::CUDAdrv.CuDevice, ::Any, ::Any) at /home/ubuntu/.julia/v0.6/CUDAnative/src/jit.jl:488
 [9] macro expansion at /home/ubuntu/.julia/v0.6/CUDAnative/src/execution.jl:107 [inlined]
 [10] _cuda(::Tuple{Int64,Int64}, ::Int64, ::CUDAdrv.CuStream, ::CuArrays.#broadcast_kernel, ::##3#4, ::CUDAnative.CuDeviceArray{Float64,1,CUDAnative.AS.Global}, ::Tuple{Tuple{Bool}}, ::Tuple{Tuple{Int64}}, ::CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, ::Tuple{}) at /home/ubuntu/.julia/v0.6/CUDAnative/src/execution.jl:80
 [11] _broadcast! at /home/ubuntu/.julia/v0.6/CuArrays/src/broadcast.jl:22 [inlined]
 [12] broadcast_t at /home/ubuntu/.julia/v0.6/CuArrays/src/broadcast.jl:37 [inlined]
 [13] broadcast_c at /home/ubuntu/.julia/v0.6/CuArrays/src/broadcast.jl:58 [inlined]
 [14] broadcast(::Function, ::CuArray{Float32,1}) at ./broadcast.jl:455

julia> x2 .^ 4.0f0
ERROR: LLVM error: Cannot select: 0x240c3670: f32 = fpow 0x240c3210, ConstantFP:f32<4.000000e+00>
  0x240c3210: f32,ch = load<LD4[null(addrspace=101)]> 0x2497acc0, TargetExternalSymbol:i64'julia__5_63777_param_0', undef:i64
    0x240c3130: i64 = TargetExternalSymbol'julia__5_63777_param_0'
    0x240c31a0: i64 = undef
  0x240c3600: f32 = ConstantFP<4.000000e+00>
In function: julia__5_63777
Stacktrace:
 [1] handle_error(::Cstring) at /home/ubuntu/.julia/v0.6/LLVM/src/core/context.jl:100
 [2] macro expansion at /home/ubuntu/.julia/v0.6/LLVM/src/base.jl:22 [inlined]
 [3] LLVMTargetMachineEmitToMemoryBuffer(::Ptr{LLVM.API.LLVMOpaqueTargetMachine}, ::Ptr{LLVM.API.LLVMOpaqueModule}, ::UInt32, ::Base.RefValue{Cstring}, ::Base.RefValue{Ptr{LLVM.API.LLVMOpaqueMemoryBuffer}}) at /home/ubuntu/.julia/v0.6/LLVM/src/../lib/3.9/libLLVM_h.jl:301
 [4] emit(::LLVM.TargetMachine, ::LLVM.Module, ::UInt32) at /home/ubuntu/.julia/v0.6/LLVM/src/targetmachine.jl:42
 [5] #mcgen#57(::Bool, ::Function, ::LLVM.Module, ::LLVM.Function, ::VersionNumber) at /home/ubuntu/.julia/v0.6/CUDAnative/src/jit.jl:393
 [6] (::CUDAnative.#kw##mcgen)(::Array{Any,1}, ::CUDAnative.#mcgen, ::LLVM.Module, ::LLVM.Function, ::VersionNumber) at ./<missing>:0
 [7] #compile_function#58(::Bool, ::Function, ::Any, ::Any, ::VersionNumber) at /home/ubuntu/.julia/v0.6/CUDAnative/src/jit.jl:440
 [8] cufunction(::CUDAdrv.CuDevice, ::Any, ::Any) at /home/ubuntu/.julia/v0.6/CUDAnative/src/jit.jl:488
 [9] macro expansion at /home/ubuntu/.julia/v0.6/CUDAnative/src/execution.jl:107 [inlined]
 [10] _cuda(::Tuple{Int64,Int64}, ::Int64, ::CUDAdrv.CuStream, ::CuArrays.#broadcast_kernel, ::##5#6, ::CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, ::Tuple{Tuple{Bool}}, ::Tuple{Tuple{Int64}}, ::CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, ::Tuple{}) at /home/ubuntu/.julia/v0.6/CUDAnative/src/execution.jl:80
 [11] _broadcast! at /home/ubuntu/.julia/v0.6/CuArrays/src/broadcast.jl:22 [inlined]
 [12] broadcast_t at /home/ubuntu/.julia/v0.6/CuArrays/src/broadcast.jl:37 [inlined]
 [13] broadcast_c at /home/ubuntu/.julia/v0.6/CuArrays/src/broadcast.jl:58 [inlined]
 [14] broadcast(::Function, ::CuArray{Float32,1}) at ./broadcast.jl:455

julia>
```

### LINKED ISSUE #659: argmax (i.e. findmax) fails with Bool arrays
**Describe the bug**

`argmax(x)` fails when `x isa CuArray{Bool}`. It does not error if `x isa CuArray{Float32}` of 1s/0s.

**To reproduce**

```julia
julia> x = cu([true false; false true])
2×2 CuArray{Bool,2}:
 1  0
 0  1

julia> argmax(x)
ERROR: InvalidIRError: compiling kernel partial_mapreduce_grid(typeof(identity), CUDA.var"#f#892"{typeof(CUDA.max),typeof(>)}, Tuple{Bool,CartesianIndex{2}}, CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}, CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}, Val{false}, CuDeviceArray{Tuple{Bool,CartesianIndex{2}},3,1}, Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2},Tuple{Base.OneTo{Int64},Base.OneTo{Int64}},typeof(tuple),Tuple{CuDeviceArray{Bool,2,1},CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}}}) resulted in invalid LLVM IR
Reason: unsupported dynamic function invocation (call to min)
Stacktrace:
 [1] f at /home/daruwalla/.julia/packages/CUDA/FlHUF/src/indexing.jl:126
 [2] multiple call sites at unknown:0
Stacktrace:
 [1] check_ir(::GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget,CUDA.CUDACompilerParams}, ::LLVM.Module) at /home/daruwalla/.julia/packages/GPUCompiler/uTpNx/src/validation.jl:123
 [2] macro expansion at /home/daruwalla/.julia/packages/GPUCompiler/uTpNx/src/driver.jl:239 [inlined]
 [3] macro expansion at /home/daruwalla/.julia/packages/TimerOutputs/ZmKD7/src/TimerOutput.jl:206 [inlined]
 [4] codegen(::Symbol, ::GPUCompiler.CompilerJob; libraries::Bool, deferred_codegen::Bool, optimize::Bool, strip::Bool, validate::Bool, only_entry::Bool) at /home/daruwalla/.julia/packages/GPUCompiler/uTpNx/src/driver.jl:237
 [5] compile(::Symbol, ::GPUCompiler.CompilerJob; libraries::Bool, deferred_codegen::Bool, optimize::Bool, strip::Bool, validate::Bool, only_entry::Bool) at /home/daruwalla/.julia/packages/GPUCompiler/uTpNx/src/driver.jl:39
 [6] compile at /home/daruwalla/.julia/packages/GPUCompiler/uTpNx/src/driver.jl:35 [inlined]
 [7] cufunction_compile(::GPUCompiler.FunctionSpec; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/daruwalla/.julia/packages/CUDA/FlHUF/src/compiler/execution.jl:302
 [8] cufunction_compile(::GPUCompiler.FunctionSpec) at /home/daruwalla/.julia/packages/CUDA/FlHUF/src/compiler/execution.jl:297
 [9] check_cache(::Dict{UInt64,Any}, ::Any, ::Any, ::GPUCompiler.FunctionSpec{typeof(CUDA.partial_mapreduce_grid),Tuple{typeof(identity),CUDA.var"#f#892"{typeof(CUDA.max),typeof(>)},Tuple{Bool,CartesianIndex{2}},CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}},CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}},Val{false},CuDeviceArray{Tuple{Bool,CartesianIndex{2}},3,1},Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2},Tuple{Base.OneTo{Int64},Base.OneTo{Int64}},typeof(tuple),Tuple{CuDeviceArray{Bool,2,1},CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}}}}}, ::UInt64; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/daruwalla/.julia/packages/GPUCompiler/uTpNx/src/cache.jl:40
 [10] partial_mapreduce_grid at /home/daruwalla/.julia/packages/CUDA/FlHUF/src/mapreduce.jl:87 [inlined]
 [11] cached_compilation at /home/daruwalla/.julia/packages/GPUCompiler/uTpNx/src/cache.jl:65 [inlined]
 [12] cufunction(::typeof(CUDA.partial_mapreduce_grid), ::Type{Tuple{typeof(identity),CUDA.var"#f#892"{typeof(CUDA.max),typeof(>)},Tuple{Bool,CartesianIndex{2}},CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}},CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}},Val{false},CuDeviceArray{Tuple{Bool,CartesianIndex{2}},3,1},Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2},Tuple{Base.OneTo{Int64},Base.OneTo{Int64}},typeof(tuple),Tuple{CuDeviceArray{Bool,2,1},CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}}}}}; name::Nothing, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/daruwalla/.julia/packages/CUDA/FlHUF/src/compiler/execution.jl:289
 [13] cufunction at /home/daruwalla/.julia/packages/CUDA/FlHUF/src/compiler/execution.jl:286 [inlined]
 [14] macro expansion at /home/daruwalla/.julia/packages/CUDA/FlHUF/src/compiler/execution.jl:100 [inlined]
 [15] mapreducedim!(::typeof(identity), ::CUDA.var"#f#892"{typeof(CUDA.max),typeof(>)}, ::CuArray{Tuple{Bool,CartesianIndex{2}},2}, ::Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2},Tuple{Base.OneTo{Int64},Base.OneTo{Int64}},typeof(tuple),Tuple{CuArray{Bool,2},CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}}}; init::Tuple{Bool,CartesianIndex{2}}) at /home/daruwalla/.julia/packages/CUDA/FlHUF/src/mapreduce.jl:192
 [16] _mapreduce(::typeof(tuple), ::CUDA.var"#f#892"{typeof(CUDA.max),typeof(>)}, ::CuArray{Bool,2}, ::CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}; dims::Colon, init::Tuple{Bool,CartesianIndex{2}}) at /home/daruwalla/.julia/packages/GPUArrays/WV76E/src/host/mapreduce.jl:62
 [17] #mapreduce#15 at /home/daruwalla/.julia/packages/GPUArrays/WV76E/src/host/mapreduce.jl:28 [inlined]
 [18] #findminmax#889 at /home/daruwalla/.julia/packages/CUDA/FlHUF/src/indexing.jl:133 [inlined]
 [19] #findmax#895 at /home/daruwalla/.julia/packages/CUDA/FlHUF/src/indexing.jl:143 [inlined]
 [20] #argmax#656 at ./reducedim.jl:952 [inlined]
 [21] argmax(::CuArray{Bool,2}) at ./reducedim.jl:952
 [22] top-level scope at REPL[47]:1
```

<details><summary>Manifest.toml</summary>
<p>

```
# This file is machine-generated - editing it directly is not advised

[[AbstractFFTs]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "051c95d6836228d120f5f4b984dd5aba1624f716"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.5.0"

[[AbstractTrees]]
deps = ["Markdown"]
git-tree-sha1 = "33e450545eaf7699da1a6e755f9ea65f14077a45"
uuid = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
version = "0.3.3"

[[Adapt]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "27edd95a09fd428113ca019c092e8aeca2eb1f2d"
uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
version = "3.0.0"

[[Artifacts]]
deps = ["Pkg"]
git-tree-sha1 = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744"
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
version = "1.3.0"

[[AxisAlgorithms]]
deps = ["LinearAlgebra", "Random", "SparseArrays", "WoodburyMatrices"]
git-tree-sha1 = "a4d07a1c313392a77042855df46c5f534076fab9"
uuid = "13072b0f-2c55-5437-9ae7-d433b7a33950"
version = "1.0.0"

[[AxisArrays]]
deps = ["Dates", "IntervalSets", "IterTools", "RangeArrays"]
git-tree-sha1 = "f31f50712cbdf40ee8287f0443b57503e34122ef"
uuid = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
version = "0.4.3"

[[BFloat16s]]
deps = ["LinearAlgebra", "Test"]
git-tree-sha1 = "4af69e205efc343068dc8722b8dfec1ade89254a"
uuid = "ab4f0b2a-ad5b-11e8-123f-65d77653426b"
version = "0.1.0"

[[BSON]]
git-tree-sha1 = "dd36d7cf3d185eeaaf64db902c15174b22f5dafb"
uuid = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
version = "0.2.6"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[Blosc]]
deps = ["Blosc_jll"]
git-tree-sha1 = "84cf7d0f8fd46ca6f1b3e0305b4b4a37afe50fd6"
uuid = "a74b3585-a348-5f62-a45c-50e91977d574"
version = "0.7.0"

[[Blosc_jll]]
deps = ["Libdl", "Lz4_jll", "Pkg", "Zlib_jll", "Zstd_jll"]
git-tree-sha1 = "aa9ef39b54a168c3df1b2911e7797e4feee50fbe"
uuid = "0b7ba130-8d10-5ba8-a3d6-c5182647fed9"
version = "1.14.3+1"

[[BufferedStreams]]
deps = ["Compat", "Test"]
git-tree-sha1 = "5d55b9486590fdda5905c275bb21ce1f0754020f"
uuid = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
version = "1.0.0"

[[CEnum]]
git-tree-sha1 = "215a9aa4a1f23fbd05b92769fdd62559488d70e9"
uuid = "fa961155-64e5-5f13-b03f-caf6b980ea82"
version = "0.4.1"

[[CUDA]]
deps = ["AbstractFFTs", "Adapt", "BFloat16s", "CEnum", "CompilerSupportLibraries_jll", "DataStructures", "ExprTools", "GPUArrays", "GPUCompiler", "LLVM", "Libdl", "LinearAlgebra", "Logging", "MacroTools", "NNlib", "Pkg", "Printf", "Random", "Reexport", "Requires", "SparseArrays", "Statistics", "TimerOutputs"]
git-tree-sha1 = "39f6f584bec264ace76f924d1c8637c85617697e"
uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
version = "2.4.0"

[[CatIndices]]
deps = ["CustomUnitRanges", "OffsetArrays"]
git-tree-sha1 = "0c91e4fcda51bbd881c5d49ef784460750abcac0"
uuid = "aafaddc9-749c-510e-ac4f-586e18779b91"
version = "0.2.1"

[[ChainRules]]
deps = ["ChainRulesCore", "Compat", "LinearAlgebra", "Random", "Reexport", "Requires", "Statistics"]
git-tree-sha1 = "31b28f5123afa5e5ca0c885e4051896032754578"
uuid = "082447d4-558c-5d27-93f4-14fc19e9eca2"
version = "0.7.45"

[[ChainRulesCore]]
deps = ["LinearAlgebra", "SparseArrays"]
git-tree-sha1 = "0acfdec745cb4cb38ad23c8668a1b7e58b42594a"
uuid = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
version = "0.9.25"

[[CodecZlib]]
deps = ["TranscodingStreams", "Zlib_jll"]
git-tree-sha1 = "ded953804d019afa9a3f98981d99b33e3db7b6da"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.7.0"

[[ColorBlendModes]]
deps = ["ColorTypes", "FixedPointNumbers"]
git-tree-sha1 = "3e7a353feb6c9f5c78a076bfeee52af6b67c3cc9"
uuid = "60508b50-96e1-4007-9d6c-f475c410f16b"
version = "0.2.2"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "4bffea7ed1a9f0f3d1a131bbcd4b925548d75288"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.10.9"

[[ColorVectorSpace]]
deps = ["ColorTypes", "Colors", "FixedPointNumbers", "LinearAlgebra", "SpecialFunctions", "Statistics", "StatsBase"]
git-tree-sha1 = "4d17724e99f357bfd32afa0a9e2dda2af31a9aea"
uuid = "c3611d14-8923-5661-9e6a-0046d554d3a4"
version = "0.8.7"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Reexport"]
git-tree-sha1 = "ac5f2213e56ed8a34a3dd2f681f4df1166b34929"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.12.6"

[[CommonSubexpressions]]
deps = ["MacroTools", "Test"]
git-tree-sha1 = "7b8a93dba8af7e3b42fecabf646260105ac373f7"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
version = "0.3.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "SHA", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "919c7f3151e79ff196add81d7f4e45d91bbf420b"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "3.25.0"

[[CompilerSupportLibraries_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "8e695f735fca77e9708e795eda62afdb869cbb70"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version = "0.3.4+0"

[[ComputationalResources]]
git-tree-sha1 = "52cb3ec90e8a8bea0e62e275ba577ad0f74821f7"
uuid = "ed09eef8-17a6-5b46-8889-db040fac31e3"
version = "0.3.2"

[[ConstructionBase]]
git-tree-sha1 = "a2a6a5fea4d6f730ec4c18a76d27ec10e8ec1c50"
uuid = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
version = "1.0.0"

[[CoordinateTransformations]]
deps = ["LinearAlgebra", "StaticArrays"]
git-tree-sha1 = "6d1c23e740a586955645500bbec662476204a52c"
uuid = "150eb455-5306-5404-9cee-2592286d6298"
version = "0.6.1"

[[CustomUnitRanges]]
git-tree-sha1 = "0d42a23be3acfb3c58569b28ed3ab8bd67af5ced"
uuid = "dc8bdbbb-1ca9-579f-8c36-e416f6a65cce"
version = "1.0.0"

[[DataAPI]]
git-tree-sha1 = "ad84f52c0b8f05aa20839484dbaf01690b41ff84"
uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
version = "1.4.0"

[[DataAugmentation]]
deps = ["ColorBlendModes", "CoordinateTransformations", "DocStringExtensions", "ImageDraw", "ImageTransformations", "Images", "Interpolations", "LinearAlgebra", "Parameters", "Rotations", "Setfield", "StaticArrays", "Statistics"]
git-tree-sha1 = "dbd4e79d2fa68aa7c820c925d5c1b7d01ffda178"
repo-rev = "master"
repo-url = "https://github.com/lorenzoh/DataAugmentation.jl"
uuid = "88a5189c-e7ff-4f85-ac6b-e6158070f02e"
version = "0.1.0"

[[DataLoaders]]
deps = ["DocStringExtensions", "LearnBase", "MLDataPattern", "Parameters", "Random", "ThreadPools"]
git-tree-sha1 = "5ca678562d2cbb0417f56b31ef083b31c654c9ce"
uuid = "2e981812-ef13-4a9c-bfa0-ab13047b12a9"
version = "0.1.2"

[[DataStructures]]
deps = ["Compat", "InteractiveUtils", "OrderedCollections"]
git-tree-sha1 = "fb0aa371da91c1ff9dc7fbed6122d3e411420b9c"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.18.8"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[DiffResults]]
deps = ["StaticArrays"]
git-tree-sha1 = "c18e98cba888c6c25d1c3b048e4b3380ca956805"
uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
version = "1.0.3"

[[DiffRules]]
deps = ["NaNMath", "Random", "SpecialFunctions"]
git-tree-sha1 = "214c3fcac57755cfda163d91c58893a8723f93e9"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "1.0.2"

[[Distances]]
deps = ["LinearAlgebra", "Statistics"]
git-tree-sha1 = "e8b13ba5f166e11df2de6fc283e5db7864245df0"
uuid = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
version = "0.10.0"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DocStringExtensions]]
deps = ["LibGit2", "Markdown", "Pkg", "Test"]
git-tree-sha1 = "50ddf44c53698f5e784bbebb3f4b21c5807401b1"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.8.3"

[[EllipsisNotation]]
git-tree-sha1 = "18ee049accec8763be17a933737c1dd0fdf8673a"
uuid = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
version = "1.0.0"

[[ExprTools]]
git-tree-sha1 = "10407a39b87f29d47ebaca8edbc75d7c302ff93e"
uuid = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
version = "0.1.3"

[[FFTViews]]
deps = ["CustomUnitRanges", "FFTW"]
git-tree-sha1 = "70a0cfd9b1c86b0209e38fbfe6d8231fd606eeaf"
uuid = "4f61f5a4-77b1-5117-aa51-3ab5ef4ef0cd"
version = "0.3.1"

[[FFTW]]
deps = ["AbstractFFTs", "FFTW_jll", "IntelOpenMP_jll", "Libdl", "LinearAlgebra", "MKL_jll", "Reexport"]
git-tree-sha1 = "8fda0934cb99db617171f7296dc361f4d6fa5424"
uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
version = "1.3.0"

[[FFTW_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "5a0d4b6a22a34d17d53543bd124f4b08ed78e8b0"
uuid = "f5851436-0d7a-5f13-b9de-f02708fd171a"
version = "3.3.9+7"

[[FileIO]]
deps = ["Pkg"]
git-tree-sha1 = "fee8955b9dfa7bec67117ef48085fb2b559b9c22"
uuid = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
version = "1.4.5"

[[FillArrays]]
deps = ["LinearAlgebra", "Random", "SparseArrays"]
git-tree-sha1 = "ff537e5a3cba92fb48f30fec46723510450f2c0e"
uuid = "1a297f60-69ca-5386-bcde-b61e274b549b"
version = "0.10.2"

[[FixedPointNumbers]]
deps = ["Statistics"]
git-tree-sha1 = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.4"

[[Flux]]
deps = ["AbstractTrees", "Adapt", "CUDA", "CodecZlib", "Colors", "DelimitedFiles", "Functors", "Juno", "LinearAlgebra", "MacroTools", "NNlib", "Pkg", "Printf", "Random", "Reexport", "SHA", "Statistics", "StatsBase", "Test", "ZipFile", "Zygote"]
git-tree-sha1 = "d4d00736320782547fc0796d22a59e7960a4c958"
repo-rev = "master"
repo-url = "https://github.com/FluxML/Flux.jl.git"
uuid = "587475ba-b771-5e3f-ad9e-33799f191a9c"
version = "0.12.0-dev"

[[ForwardDiff]]
deps = ["CommonSubexpressions", "DiffResults", "DiffRules", "NaNMath", "Random", "SpecialFunctions", "StaticArrays"]
git-tree-sha1 = "8de2519a83c6c1c2442c2f481dd9a8364855daf4"
uuid = "f6369f11-7733-5829-9624-2563aa707210"
version = "0.10.14"

[[Functors]]
deps = ["MacroTools"]
git-tree-sha1 = "f40adc6422f548176bb4351ebd29e4abf773040a"
uuid = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
version = "0.1.0"

[[Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"

[[GPUArrays]]
deps = ["AbstractFFTs", "Adapt", "LinearAlgebra", "Printf", "Random", "Serialization"]
git-tree-sha1 = "f99a25fe0313121f2f9627002734c7d63b4dd3bd"
uuid = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
version = "6.2.0"

[[GPUCompiler]]
deps = ["DataStructures", "InteractiveUtils", "LLVM", "Libdl", "Scratch", "Serialization", "TimerOutputs", "UUIDs"]
git-tree-sha1 = "c853c810b52a80f9aad79ab109207889e57f41ef"
uuid = "61eb1bfa-7361-4325-ad38-22787b887f55"
version = "0.8.3"

[[Graphics]]
deps = ["Colors", "LinearAlgebra", "NaNMath"]
git-tree-sha1 = "45d684ead5b65c043ad46bd5be750d61c39d7ef8"
uuid = "a2bd30eb-e257-5431-a919-1863eab51364"
version = "1.0.2"

[[HDF5]]
deps = ["Blosc", "Compat", "HDF5_jll", "Libdl", "Mmap", "Random", "Requires"]
git-tree-sha1 = "8be8b31df938483ba2ab27f38a8bc91a9e43ae92"
uuid = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
version = "0.14.3"

[[HDF5_jll]]
deps = ["Artifacts", "JLLWrappers", "LibCURL_jll", "Libdl", "OpenSSL_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "fd83fa0bde42e01952757f01149dd968c06c4dba"
uuid = "0234f1f7-429e-5d53-9886-15a909be8d59"
version = "1.12.0+1"

[[IRTools]]
deps = ["InteractiveUtils", "MacroTools", "Test"]
git-tree-sha1 = "c67e7515a11f726f44083e74f218d134396d6510"
uuid = "7869d1d1-7146-5819-86e3-90919afe41df"
version = "0.4.2"

[[IdentityRanges]]
deps = ["OffsetArrays"]
git-tree-sha1 = "be8fcd695c4da16a1d6d0cd213cb88090a150e3b"
uuid = "bbac6d45-d8f3-5730-bfe4-7a449cd117ca"
version = "0.3.1"

[[ImageAxes]]
deps = ["AxisArrays", "ImageCore", "Reexport", "SimpleTraits"]
git-tree-sha1 = "1592c7fd668ac9cdcef73f704ca457ccdaac2933"
uuid = "2803e5a7-5153-5ecf-9a86-9b4c37f5f5ac"
version = "0.6.8"

[[ImageContrastAdjustment]]
deps = ["ColorVectorSpace", "ImageCore", "ImageTransformations", "Parameters"]
git-tree-sha1 = "210f8fb370d4b97fa12d65322c62df06f3e5563b"
uuid = "f332f351-ec65-5f6a-b3d1-319c6670881a"
version = "0.3.6"

[[ImageCore]]
deps = ["AbstractFFTs", "Colors", "FixedPointNumbers", "Graphics", "MappedArrays", "MosaicViews", "OffsetArrays", "PaddedViews", "Reexport"]
git-tree-sha1 = "79badd979fbee9b8980cd995cd5a86a9e93b8ad7"
uuid = "a09fc81d-aa75-5fe9-8630-4744c3626534"
version = "0.8.20"

[[ImageDistances]]
deps = ["ColorVectorSpace", "Distances", "ImageCore", "LinearAlgebra", "Statistics"]
git-tree-sha1 = "c6dcdcf7e3088603fa9151fdb63f90082ec3b4db"
uuid = "51556ac3-7006-55f5-8cb3-34580c88182d"
version = "0.2.9"

[[ImageDraw]]
deps = ["Distances", "ImageCore", "LinearAlgebra"]
git-tree-sha1 = "f391e0d5bc42df52a7004dd2c656736667e85115"
uuid = "4381153b-2b60-58ae-a1ba-fd683676385f"
version = "0.2.4"

[[ImageFiltering]]
deps = ["CatIndices", "ColorVectorSpace", "ComputationalResources", "DataStructures", "FFTViews", "FFTW", "ImageCore", "ImageMetadata", "LinearAlgebra", "OffsetArrays", "Requires", "SparseArrays", "StaticArrays", "Statistics", "TiledIteration"]
git-tree-sha1 = "ac8321781d375dd0ac8571072f538866c279a216"
uuid = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
version = "0.6.18"

[[ImageMagick]]
deps = ["FileIO", "ImageCore", "ImageMagick_jll", "InteractiveUtils", "Libdl", "Pkg", "Random"]
git-tree-sha1 = "02558f83932fde6ebd3ab007dbff6bd8740a8247"
uuid = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
version = "1.1.6"

[[ImageMagick_jll]]
deps = ["JpegTurbo_jll", "Libdl", "Libtiff_jll", "Pkg", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "1c0a2295cca535fabaf2029062912591e9b61987"
uuid = "c73af94c-d91f-53ed-93a7-00f77d67a9d7"
version = "6.9.10-12+3"

[[ImageMetadata]]
deps = ["AxisArrays", "ColorVectorSpace", "ImageAxes", "ImageCore", "IndirectArrays"]
git-tree-sha1 = "ff77c7f234e7d8a618958fcf23b6959f2cbef2c6"
uuid = "bc367c6b-8a6b-528e-b4bd-a4b897500b49"
version = "0.9.4"

[[ImageMorphology]]
deps = ["ColorVectorSpace", "ImageCore", "LinearAlgebra", "TiledIteration"]
git-tree-sha1 = "113df7743f1e18da5f5ea5f98eb59ceb77092734"
uuid = "787d08f9-d448-5407-9aad-5290dd7ab264"
version = "0.2.9"

[[ImageQualityIndexes]]
deps = ["ColorVectorSpace", "ImageCore", "ImageDistances", "ImageFiltering", "OffsetArrays", "Statistics"]
git-tree-sha1 = "80484f9e1beae36860ed8022f195d04c751cfec6"
uuid = "2996bd0c-7a13-11e9-2da2-2f5ce47296a9"
version = "0.2.1"

[[ImageShow]]
deps = ["Base64", "FileIO", "ImageCore", "Requires"]
git-tree-sha1 = "c9df184bc7c2e665f971079174aabb7d18f1845f"
uuid = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
version = "0.2.3"

[[ImageTransformations]]
deps = ["AxisAlgorithms", "ColorVectorSpace", "CoordinateTransformations", "IdentityRanges", "ImageCore", "Interpolations", "OffsetArrays", "Rotations", "StaticArrays"]
git-tree-sha1 = "b9ed11686a335d7f981e97ddc588f81b1a6f5fa3"
uuid = "02fcd773-0e25-5acc-982a-7f6622650795"
version = "0.8.8"

[[Images]]
deps = ["AxisArrays", "Base64", "ColorVectorSpace", "FileIO", "Graphics", "ImageAxes", "ImageContrastAdjustment", "ImageCore", "ImageDistances", "ImageFiltering", "ImageMetadata", "ImageMorphology", "ImageQualityIndexes", "ImageShow", "ImageTransformations", "IndirectArrays", "OffsetArrays", "Random", "Reexport", "SparseArrays", "StaticArrays", "Statistics", "StatsBase", "TiledIteration"]
git-tree-sha1 = "535bcaae047f017f4fd7331ee859b75f2b27e505"
uuid = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
version = "0.23.3"

[[IndirectArrays]]
git-tree-sha1 = "c2a145a145dc03a7620af1444e0264ef907bd44f"
uuid = "9b13fd28-a010-5f03-acff-a1bbcff69959"
version = "0.5.1"

[[IntelOpenMP_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "fb8e1c7a5594ba56f9011310790e03b5384998d6"
uuid = "1d5cc7b8-4909-519e-a0f8-d0f5ad9712d0"
version = "2018.0.3+0"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Interpolations]]
deps = ["AxisAlgorithms", "LinearAlgebra", "OffsetArrays", "Random", "Ratios", "SharedArrays", "SparseArrays", "StaticArrays", "WoodburyMatrices"]
git-tree-sha1 = "eb1dd6d5b2275faaaa18533e0fc5f9171cec25fa"
uuid = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
version = "0.13.1"

[[IntervalSets]]
deps = ["Dates", "EllipsisNotation", "Statistics"]
git-tree-sha1 = "93a6d78525feb0d3ee2a2ae83a7d04db1db5663f"
uuid = "8197267c-284f-5f27-9208-e0e47529a953"
version = "0.5.2"

[[IterTools]]
git-tree-sha1 = "05110a2ab1fc5f932622ffea2a003221f4782c18"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.3.0"

[[JLLWrappers]]
git-tree-sha1 = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.2.0"

[[JpegTurbo_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9aff0587d9603ea0de2c6f6300d9f9492bbefbd3"
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
version = "2.0.1+3"

[[Juno]]
deps = ["Base64", "Logging", "Media", "Profile"]
git-tree-sha1 = "07cb43290a840908a771552911a6274bc6c072c7"
uuid = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
version = "0.8.4"

[[LLVM]]
deps = ["CEnum", "Libdl", "Printf", "Unicode"]
git-tree-sha1 = "d0d99629d6ae4a3e211ae83d8870907bd842c811"
uuid = "929cbde3-209d-540e-8aea-75f648917ca0"
version = "3.5.2"

[[LearnBase]]
deps = ["LinearAlgebra", "StatsBase"]
git-tree-sha1 = "47e6f4623c1db88570c7a7fa66c6528b92ba4725"
uuid = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
version = "0.3.0"

[[LibCURL_jll]]
deps = ["LibSSH2_jll", "Libdl", "MbedTLS_jll", "Pkg", "Zlib_jll", "nghttp2_jll"]
git-tree-sha1 = "897d962c20031e6012bba7b3dcb7a667170dad17"
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
version = "7.70.0+2"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[LibSSH2_jll]]
deps = ["Libdl", "MbedTLS_jll", "Pkg"]
git-tree-sha1 = "717705533148132e5466f2924b9a3657b16158e8"
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"
version = "1.9.0+3"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libtiff_jll]]
deps = ["Artifacts", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Pkg", "Zlib_jll", "Zstd_jll"]
git-tree-sha1 = "291dd857901f94d683973cdf679984cdf73b56d0"
uuid = "89763e89-9b03-5906-acba-b20f662cd828"
version = "4.1.0+2"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Lz4_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "51b1db0732bbdcfabb60e36095cc3ed9c0016932"
uuid = "5ced341a-0733-55b8-9ab6-a4889d929147"
version = "1.9.2+2"

[[MAT]]
deps = ["BufferedStreams", "CodecZlib", "HDF5", "SparseArrays"]
git-tree-sha1 = "2b8a117b0748d0e0cd1b8a8edfea24898e2b00d1"
uuid = "23992714-dd62-5051-b70f-ba57cb901cac"
version = "0.10.0"

[[MKL_jll]]
deps = ["IntelOpenMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "eb540ede3aabb8284cb482aa41d00d6ca850b1f8"
uuid = "856f044c-d86e-5d09-b602-aeab76dc8ba7"
version = "2020.2.254+0"

[[MLDataPattern]]
deps = ["LearnBase", "MLLabelUtils", "Random", "SparseArrays", "StatsBase"]
git-tree-sha1 = "e99514e96e8b8129bb333c69e063a56ab6402b5b"
uuid = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
version = "0.5.4"

[[MLLabelUtils]]
deps = ["LearnBase", "MappedArrays", "StatsBase"]
git-tree-sha1 = "71d874f2e97bf01dc5c44d562cea30cc7ebb81d1"
uuid = "66a33bbf-0c2b-5fc8-a008-9da813334f0a"
version = "0.5.5"

[[MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "6a8a2a625ab0dea913aba95c11370589e0239ff0"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.6"

[[MappedArrays]]
deps = ["FixedPointNumbers"]
git-tree-sha1 = "b92bd220c95a8bbe89af28f11201fd080e0e3fe7"
uuid = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
version = "0.3.0"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[MbedTLS_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "0eef589dd1c26a3ac9d753fe1a8bcad63f956fa6"
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
version = "2.16.8+1"

[[Media]]
deps = ["MacroTools", "Test"]
git-tree-sha1 = "75a54abd10709c01f1b86b84ec225d26e840ed58"
uuid = "e89f7d12-3494-54d1-8411-f7d8b9ae1f27"
version = "0.5.0"

[[Metalhead]]
deps = ["BSON", "Flux"]
git-tree-sha1 = "450e361232c386968ed0b22bc99d1c9964c969a2"
repo-rev = "darsnack/vision-refactor"
repo-url = ".."
uuid = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
version = "0.5.1"

[[Missings]]
deps = ["DataAPI"]
git-tree-sha1 = "ed61674a0864832495ffe0a7e889c0da76b0f4c8"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.4.4"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[MosaicViews]]
deps = ["MappedArrays", "OffsetArrays", "PaddedViews"]
git-tree-sha1 = "614e8d77264d20c1db83661daadfab38e8e4b77e"
uuid = "e94cdb99-869f-56ef-bcf0-1ae2bcbe0389"
version = "0.2.4"

[[NNlib]]
deps = ["ChainRulesCore", "LinearAlgebra", "Pkg", "Requires", "Statistics"]
git-tree-sha1 = "13fd29731c7f609cb82a3a544c5538584d22c153"
uuid = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
version = "0.7.11"

[[NaNMath]]
git-tree-sha1 = "bfe47e760d60b82b66b61d2d44128b62e3a369fb"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.5"

[[OffsetArrays]]
git-tree-sha1 = "a416e2f267e2c8729f25bcaf1ce19d2893faf393"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "1.3.1"

[[OpenSSL_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "71bbbc616a1d710879f5a1021bcba65ffba6ce58"
uuid = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
version = "1.1.1+6"

[[OpenSpecFun_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9db77584158d0ab52307f8c04f8e7c08ca76b5b3"
uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
version = "0.5.3+4"

[[OrderedCollections]]
git-tree-sha1 = "cf59cfed2e2c12e8a2ff0a4f1e9b2cd8650da6db"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.3.2"

[[PaddedViews]]
deps = ["OffsetArrays"]
git-tree-sha1 = "91d229e113e8975a399e40d7c0b1ddf4da6d3c59"
uuid = "5432bcbf-9aad-5242-b902-cca2824c8663"
version = "0.5.7"

[[ParameterSchedulers]]
git-tree-sha1 = "887960ce713abb043c1b3f52bca3de92d8ab3720"
uuid = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
version = "0.1.0"

[[Parameters]]
deps = ["OrderedCollections", "UnPack"]
git-tree-sha1 = "38b2e970043613c187bd56a995fe2e551821eb4a"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.12.1"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Profile]]
deps = ["Printf"]
uuid = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RangeArrays]]
git-tree-sha1 = "b9039e93773ddcfc828f12aadf7115b4b4d225f5"
uuid = "b3c3ace0-ae52-54e7-9d0b-2c1406fd6b9d"
version = "0.3.2"

[[Ratios]]
git-tree-sha1 = "37d210f612d70f3f7d57d488cb3b6eff56ad4e41"
uuid = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
version = "0.4.0"

[[RecipesBase]]
git-tree-sha1 = "b3fb709f3c97bfc6e948be68beeecb55a0b340ae"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "1.1.1"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "cfbac6c1ed70c002ec6361e7fd334f02820d6419"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.1.2"

[[Rotations]]
deps = ["LinearAlgebra", "StaticArrays", "Statistics"]
git-tree-sha1 = "2ed8d8a16d703f900168822d83699b8c3c1a5cd8"
uuid = "6038ab10-8711-5258-84ad-4b1120ba62dc"
version = "1.0.2"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Scratch]]
deps = ["Dates"]
git-tree-sha1 = "ad4b278adb62d185bbcb6864dc24959ab0627bf6"
uuid = "6c6a2e73-6563-6170-7368-637461726353"
version = "1.0.3"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Setfield]]
deps = ["ConstructionBase", "Future", "MacroTools", "Requires"]
git-tree-sha1 = "d5640fc570fb1b6c54512f0bd3853866bd298b3e"
uuid = "efcf1570-3423-57d1-acb7-fd33fddbac46"
version = "0.7.0"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[SimpleTraits]]
deps = ["InteractiveUtils", "MacroTools"]
git-tree-sha1 = "daf7aec3fe3acb2131388f93a4c409b8c7f62226"
uuid = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
version = "0.9.3"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "03f5898c9959f8115e30bc7226ada7d0df554ddd"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.1"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["ChainRulesCore", "OpenSpecFun_jll"]
git-tree-sha1 = "75394dbe2bd346beeed750fb02baa6445487b862"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "1.2.1"

[[StaticArrays]]
deps = ["LinearAlgebra", "Random", "Statistics"]
git-tree-sha1 = "9da72ed50e94dbff92036da395275ed114e04d49"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "1.0.1"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataAPI", "DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics"]
git-tree-sha1 = "7bab7d4eb46b225b35179632852b595a3162cb61"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.33.2"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[ThreadPools]]
deps = ["Printf", "RecipesBase", "Statistics"]
git-tree-sha1 = "705ccc29d575b87cceb359dfea19f4653d06df8f"
uuid = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
version = "1.2.1"

[[TiledIteration]]
deps = ["OffsetArrays"]
git-tree-sha1 = "05f74c5b3c00d5336bc109416df2df907e3bd91d"
uuid = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"
version = "0.2.5"

[[TimerOutputs]]
deps = ["Printf"]
git-tree-sha1 = "3318281dd4121ecf9713ce1383b9ace7d7476fdd"
uuid = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
version = "0.5.7"

[[TranscodingStreams]]
deps = ["Random", "Test"]
git-tree-sha1 = "7c53c35547de1c5b9d46a4797cf6d8253807108c"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.9.5"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[UnPack]]
git-tree-sha1 = "387c1f73762231e86e0c9c5443ce3b4a0a9a0c2b"
uuid = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
version = "1.0.2"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[WoodburyMatrices]]
deps = ["LinearAlgebra", "SparseArrays"]
git-tree-sha1 = "59e2ad8fd1591ea019a5259bd012d7aee15f995c"
uuid = "efce3f68-66dc-5838-9240-27a6d6f5f9b6"
version = "0.5.3"

[[ZipFile]]
deps = ["Libdl", "Printf", "Zlib_jll"]
git-tree-sha1 = "c3a5637e27e914a7a445b8d0ad063d701931e9f7"
uuid = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
version = "0.9.3"

[[Zlib_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "320228915c8debb12cb434c59057290f0834dbf6"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.11+18"

[[Zstd_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "6f1abcb0c44f184690912aa4b0ba861dd64f11b9"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.4.5+2"

[[Zygote]]
deps = ["AbstractFFTs", "ChainRules", "DiffRules", "Distributed", "FillArrays", "ForwardDiff", "IRTools", "InteractiveUtils", "LinearAlgebra", "MacroTools", "NaNMath", "Random", "Requires", "SpecialFunctions", "Statistics", "ZygoteRules"]
git-tree-sha1 = "d88a7e71fc2eef9510187b1c7d4af7a5177633d0"
uuid = "e88e6eb3-aa80-5325-afca-941959d7151f"
version = "0.6.0"

[[ZygoteRules]]
deps = ["MacroTools"]
git-tree-sha1 = "9e7a1e8ca60b742e508a315c17eef5211e7fbfd7"
uuid = "700de1a5-db45-46bc-99cf-38207098b444"
version = "0.2.1"

[[libpng_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "6abbc424248097d69c0c87ba50fcb0753f93e0ee"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.37+6"

[[nghttp2_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "8e2c44ab4d49ad9518f359ed8b62f83ba8beede4"
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"
version = "1.40.0+2"
```

</p>
</details>

**Expected behavior**

`argmax(x)` doesn't error for `CuArray{Bool}`.

**Version info**

Details on Julia: 1.5.3

```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen Threadripper 1950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
Environment:
  JULIA_CUDA_SILENT = 0
  JULIA_CUDA_VERBOSE = 1
  JULIA_NUM_THREADS = 8
```

Details on CUDA:

```
CUDA toolkit 11.0.3, artifact installation
CUDA driver 11.0.0
NVIDIA driver 450.66.0

Libraries: 
- CUBLAS: 11.2.0
- CURAND: 10.2.1
- CUFFT: 10.2.1
- CUSOLVER: 10.6.0
- CUSPARSE: 11.1.1
- CUPTI: 13.0.0
- NVML: 11.0.0+450.66
- CUDNN: 8.0.4 (for CUDA 11.0.0)
- CUTENSOR: 1.2.1 (for CUDA 11.0.0)

Toolchain:
- Julia: 1.5.3
- LLVM: 9.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75

Environment:
- JULIA_CUDA_VERBOSE: 1
- JULIA_CUDA_SILENT: 0

1 device:
  0: TITAN Xp (sm_61, 11.580 GiB / 11.907 GiB available)
```

**Additional context**

This poses a problem for ML workloads where one hot arrays are decoded to labels.

### PR DESCRIPTION
**Pull request by maleadt**
Builds on https://github.com/JuliaGPU/GPUCompiler.jl/pull/151, requires https://github.com/JuliaLang/julia/pull/39697 on Julia 1.7 but should also work on 1.6. Supersedes https://github.com/JuliaGPU/CUDAnative.jl/pull/334.

Fixes https://github.com/JuliaGPU/CUDA.jl/issues/60

```julia
julia> CUDA.saturate(1f0)
ERROR: This function is not intended for use on the CPU
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] saturate(x::Float32)
   @ CUDA ~/Julia/pkg/CUDA/src/device/intrinsics.jl:23
 [3] top-level scope
   @ REPL[10]:1
```

Fixes https://github.com/JuliaGPU/CUDA.jl/issues/42

```julia
julia> a = CuArray([Complex(1f0,2f0)])
1-element CuArray{ComplexF32, 1}:
 1.0f0 + 2.0f0im

julia> sincos.(a)
1-element CuArray{Tuple{ComplexF32, ComplexF32}, 1}:
 (3.1657786f0 + 1.9596009f0im, 2.032723f0 - 3.0518978f0im)
```

Fixes https://github.com/JuliaGPU/CUDA.jl/issues/659

```julia
julia> x = cu([true false; false true])
2×2 CuArray{Bool, 2}:
 1  0
 0  1

julia> argmax(x)
CartesianIndex(1, 1)
```

Fixes #140:

```julia
julia> using DualNumbers
[ Info: Precompiling DualNumbers [fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74]

julia> p = CUDA.zeros(Dual128, 6)
6-element CuArray{Dual128, 1}:
 0.0 + 0.0ɛ
 0.0 + 0.0ɛ
 0.0 + 0.0ɛ
 0.0 + 0.0ɛ
 0.0 + 0.0ɛ
 0.0 + 0.0ɛ

julia> exp.(p)
6-element CuArray{Dual128, 1}:
 1.0 + 0.0ɛ
 1.0 + 0.0ɛ
 1.0 + 0.0ɛ
 1.0 + 0.0ɛ
 1.0 + 0.0ɛ
 1.0 + 0.0ɛ
```

Fixes #76:

```julia
julia> bar(x) = 1.0^x
bar (generic function with 1 method)

julia> bar.(CuArray([1]))
1-element CuArray{Float64, 1}:
 1.0
```

Fixes https://github.com/JuliaGPU/CUDA.jl/issues/71:

```julia
julia> function kernel_vpow(a, b)
           i = (blockIdx().x-1) * blockDim().x + threadIdx().x
           b[i] = a[i]^1.5
           return nothing
       end
kernel_vpow (generic function with 1 method)

julia> a = round.(rand(Float32, (3, 4)) * 100);

julia> d_a = CuArray(a);

julia> d_b = similar(d_a);

julia> @cuda kernel_vpow(d_a, d_b)
CUDA.HostKernel{kernel_vpow, Tuple{CuDeviceMatrix{Float32, 1}, CuDeviceMatrix{Float32, 1}}}(CuContext(0x00000000025d73b0, instance a0f57c0b433bf9bd), CuModule(Ptr{Nothing} @0x000000000c4fc0b0, CuContext(0x00000000025d73b0, instance a0f57c0b433bf9bd)), CuFunction(Ptr{Nothing} @0x000000000c28c6f0, CuModule(Ptr{Nothing} @0x000000000c4fc0b0, CuContext(0x00000000025d73b0, instance a0f57c0b433bf9bd))))

julia> 
```

Fixes https://github.com/JuliaGPU/CUDA.jl/issues/171:

```julia
julia> x = rand(Float32, 100);

julia> x2 = x |> cu;

julia> x2 .^ 4
100-element CuArray{Float32, 1}:
...
```

Should fix https://github.com/JuliaGPU/CUDA.jl/issues/169, but I can't reproduce the original issue.

Should fix https://github.com/JuliaGPU/CUDA.jl/issues/130.

### CODE REVIEW

File: src/initialization.jl [hunk 1]
```diff
@@ -91,7 +91,10 @@ function __init__()
         thread_streams[tid] = nothing
     end
 
-    @require ForwardDiff="f6369f11-7733-5829-9624-2563aa707210" include("forwarddiff.jl")
+    precompiling = ccall(:jl_generating_output, Cint, ()) != 0
+    if !precompiling
+        eval(overrides)
```
Comment (vchuravy) [inline src/initialization.jl:96]: `empty!(overrides.args)`?

Comment (vchuravy) [reply src/initialization.jl:96]: Particularly motivated by me wanting to do overrides in an outside package, calling this twice shouldn't hurt.

File: src/device/intrinsics.jl [hunk 2]
```diff
@@ -1,5 +1,34 @@
 # wrappers for functionality provided by the CUDA toolkit
 
+const overrides = quote end
+
+macro device_override(ex)
+    code = quote
+        GPUCompiler.@override($method_table, $ex)
```
Comment (vchuravy) [inline src/device/intrinsics.jl]:
```suggestion
        $GPUCompiler.@override($method_table, $ex)
```

Otherwise an invocation in a different module will get:
```
vchuravy@cyclops:~/dev/KernelAbstractions$ ~/julia-1.6.0-rc1/bin/julia --project=lib/CUDAKernels mt.jl 
ERROR: LoadError: InitError: LoadError: UndefVarError: GPUCompiler not defined
Stacktrace:
 [1] top-level scope
   @ :0
 [2] eval
   @ ./boot.jl:360 [inlined]
 [3] eval
   @ ~/.julia/dev/KernelAbstractions/mt.jl:1 [inlined]
 [4] __init__()
   @ Main.CUDAKernels ~/.julia/dev/KernelAbstractions/mt.jl:8
in expression starting at /home/vchuravy/.julia/packages/CUDA/9IRgE/src/device/intrinsics.jl:7
during initialization of module CUDAKernels
in expression starting at /home/vchuravy/.julia/dev/KernelAbstractions/mt.jl:1
```

File: src/initialization.jl (hunk 1 above)
Comment (vchuravy) [reply src/initialization.jl:96]: without the `empty!` you get:

```
vchuravy@cyclops:~/dev/KernelAbstractions$ ~/julia-1.6.0-rc1/bin/julia --project=lib/CUDAKernels mt.jl 
ERROR: LoadError: InitError: UndefVarError: FastMath not defined
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/GPUCompiler/gbnMW/src/jlgen.jl:156 [inlined]
 [2] top-level scope
   @ ~/.julia/packages/CUDA/9IRgE/src/device/intrinsics.jl:7
 [3] eval
   @ ./boot.jl:360 [inlined]
 [4] eval
   @ ~/.julia/dev/KernelAbstractions/mt.jl:1 [inlined]
 [5] __init__()
   @ Main.CUDAKernels ~/.julia/dev/KernelAbstractions/mt.jl:9
during initialization of module CUDAKernels
in expression starting at /home/vchuravy/.julia/dev/KernelAbstractions/mt.jl:1
```

**Comment by vchuravy** [comment]
This seems to work at a first glance:

```
module CUDAKernels

using CUDA

function __init__()
    precompiling = ccall(:jl_generating_output, Cint, ()) != 0
    if !precompiling
        eval(CUDA.overrides)
        empty!(CUDA.overrides.args)
    end
end

f() = 1
CUDA.@device_override f() = 2

function kernel(A)
    A[1] = f()
    nothing
end

end # module
```

after adding `empty!` and the `$GPUCompiler`

File: src/initialization.jl (hunk 1 above)
Comment (maleadt) [reply src/initialization.jl:96]: If you do overrides from an external package, you just want to `eval` those yourself? Calling `__init__` twice is likely going to break in other cases (double-registering hooks, re-initializating thread local caches, etc).

**Comment by maleadt** [comment]
@vchuravy I didn't include your suggestions; `@device_override` isn't intended to be reusable, and it isn't safe to call `__init__` twice. Since it's just a thin layer over the functionality from GPUArrays.jl (which _is_ intended to be reusable), you can just call that.

**Comment by vchuravy** [comment]
Can you add an warning to that effect? E.g. that `@device_override` is internal to `CUDA.jl` and not supposed to be used by external users?
On 1.7 it coulde be used by external users right? 

>  and it isn't safe to call __init__ twice.

Yeah no plans here to call `__init__` twice, More that `eval(CUDA.overrides)` could be made robust.

**Comment by maleadt** [comment]
If you want to rely on this being available externally, we could try and make that a possibility. Maybe with a convenient `register_overrides()` function then, to be called at run time.
