### PR TITLE
Use `adapt` symmetrically in `CuIterator`

### LINKED ISSUE #1768: Limitations of `CuIterator`
I think it would be nice if the following uses of CuIterator. Are these within its intended scope? 
```julia
julia> using CUDA

julia> function sumone(itr)
         x = first(itr)
         @show summary(x)
         sum(sum∘prod, itr)  # run the whole iterator
       end;

julia> sumone(CuIterator((Array(x),) for x in eachcol(ones(3,4))))  # fine
summary(x) = "Tuple{CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}"
12.0

julia> sumone(CuIterator(Array(x) for x in eachcol(ones(3,4))))  # 2, no CuArrays
summary(x) = "3-element Vector{Float64}"
ERROR: MethodError: no method matching unsafe_free!(::Float64)

julia> sumone(CuIterator((Array(x)',) for x in eachcol(ones(3,4))))  # 3, makes but can't free
summary(x) = "Tuple{LinearAlgebra.Adjoint{Float64, CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}}"
ERROR: MethodError: no method matching unsafe_free!(::LinearAlgebra.Adjoint{Float64, CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}})

julia> sumone(CuIterator((x,) for x in eachcol(ones(3,4))))  # 4, here adapt acts on whole array
summary(x) = "Tuple{SubArray{Float64, 1, CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}}"
ERROR: MethodError: no method matching unsafe_free!(::SubArray{Float64, 1, CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true})

julia> sumone(CuIterator((i, Array(x)) for (i,x) in enumerate(eachcol(ones(3,4)))))  # 5, finalize?
summary(x) = "Tuple{Int64, CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}"
```

Especially 3, where it seems surprising that the creation uses `adapt` to get inside wrappers, but the destruction does not. It seems that this could be fixed fairly simply, something like this:
```julia
julia> using Adapt

julia> Adapt.adapt_storage(::typeof(CUDA.unsafe_free!), x::CuArray) = (CUDA.unsafe_free!(x); x)

julia> let x = cu(ones(3))'
         adapt(CUDA.unsafe_free!, x)
       end;
```
The motivating case isn't Adjoint but OneHotMatrix:
```julia
julia> using OneHotArrays

julia> oh = onehotbatch([1,2,3,1,2], 1:4);

julia> cu(oh)  # adapt understands this
4×5 OneHotMatrix(::CuArray{UInt32, 1, CUDA.Mem.DeviceBuffer}) with eltype Bool:
 1  ⋅  ⋅  1  ⋅
 ⋅  1  ⋅  ⋅  1
 ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅

julia> sumone(CuIterator((x,) for x in [oh, oh]))
summary(x) = "Tuple{OneHotMatrix{UInt32, CuArray{UInt32, 1, CUDA.Mem.DeviceBuffer}}}"
ERROR: MethodError: no method matching unsafe_free!(::OneHotMatrix{UInt32, CuArray{UInt32, 1, CUDA.Mem.DeviceBuffer}})
```
Others:

It would not be very hard to make case 2 above work. Or else, to make it give an informative error the minute your iterator produces something unacceptable (an array of numbers, not a Tuple/NamedTuple of such). 

Not sure what should happen in case 4. Using `adapt` for destruction (as 3) would make it run, but very inefficiently... it's like doing this repeatedly:
```julia
julia> let x = ones(10, 10^6)
         CUDA.@time cu(x[:,1])
         CUDA.@time cu(view(x,:,1))
       end;
  0.000114 seconds (14 CPU allocations: 624 bytes) (1 GPU allocation: 40 bytes, 22.06% memmgmt time)
  0.050605 seconds (14 CPU allocations: 38.147 MiB) (1 GPU allocation: 38.147 MiB, 1.54% memmgmt time)
```
For 5, possibly the destructor should be something which does nothing on non-arrays? This could be `finalize` although perhaps not ideal:
```
julia> @btime finalize(3)
  100.176 ns (0 allocations: 0 bytes)
```

### PR DESCRIPTION
**Pull request by mcabbott**
Closes #1768

The examples there become:
```julia
julia> sumone(CuIterator((Array(x),) for x in eachcol(ones(3,4))))  # fine
summary(x) = "Tuple{CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}"
12.0

julia> sumone(CuIterator(Array(x) for x in eachcol(ones(3,4))))  # 2, no CuArrays
summary(x) = "3-element CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}"
4.0

julia> sumone(CuIterator((Array(x)',) for x in eachcol(ones(3,4))))  # 3, makes but can't free
summary(x) = "Tuple{LinearAlgebra.Adjoint{Float64, CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}}"
12.0

julia> sumone(CuIterator((x,) for x in eachcol(ones(3,4))))  # 4, here adapt acts on whole array
summary(x) = "Tuple{SubArray{Float64, 1, CuArray{Float64, 2, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}}"
12.0

julia> sumone(CuIterator((i, Array(x)) for (i,x) in enumerate(eachcol(ones(3,4)))))  # 5, finalize?
summary(x) = "Tuple{Int64, CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}"
30.0
```
Needs tests (and doc update) hence draft. But does this seem like a good idea?

### CODE REVIEW

**Comment by mcabbott** [comment]
From the tests, the case which `map(cu, x)` allows but `cu(x)` does not is `x = [ones(2) for _ in 1:3]`.

Cases above are like 1 `x = (ones(2), ones(2))` (which is what I thought `map` was for, still works) and 2 `x = ones(2)` (didn't work with `map`).

Not so hard to add cases to allow for all of these. But I wonder if there's a compact statement of what exactly is and isn't accepted by this thing.

**Comment by maleadt** [comment]
That seems sensible. I'd document that the `adapt` rule isn't functionality to rely on, though. Maybe it would be better to use a special-purpose singleton Adaptor struct for that in the `iterator.jl` sources (like we have a couple already in CUDA.jl/GPUArrays.jl) to make that very clear.

**Comment by mcabbott** [comment]
Ok, I think I see what you mean. See if [ff801b2](https://github.com/JuliaGPU/CUDA.jl/pull/1769/commits/ff801b29a4b7fb3ecce2d632af7c70fadb292878) looks promising.

File: src/array.jl [hunk 1]
```diff
@@ -649,6 +649,15 @@ julia> CuArray(1:3)
 
 Base.getindex(::typeof(cu), xs...) = CuArray([xs...])
 
+## unsafe_free!
+# This allows adapt(unsafe_free!, obj) to go whereever adapt(CuArray, obj) went,
+# so that for example CuIterator can free arrays within Adjoint.
+
+function Adapt.adapt_storage(::typeof(unsafe_free!), x::CuArray)
```
Comment (maleadt) [inline src/array.jl]: Unused?

**Comment by maleadt** [comment]
Conceptually this looks fine to me, but I didn't design CuIterator nor do I have much experience with it, so I'll defer to you for this PR.
