### PR TITLE
[CUSOLVER] Update gesvdp!

### LINKED ISSUE #2761: `Xgesvdp!` failure when only requesting singular values
**Describe the bug**

I am trying to use the CUSOLVER `Xgesvdp!` method, which computes the singular value decomposition via polar decomposition and symmetric eigenvalue decomposition of the positive factor. It works when requesting both singular values and singular vectors, but not when only requesting singular values. I did not manage to decipher what is causing this bug:

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia-repl
julia> using CUDA, LinearAlgebra

julia> A = CUDA.randn(Float64, 10, 10);

julia> U, S, V, err = CUDA.CUSOLVER.Xgesvdp!('V', 0, copy(A));

julia> A ≈ U * Diagonal(S) * V' # succes!
true

julia> S, err = CUDA.CUSOLVER.Xgesvdp!('N', 1, copy(A));
ERROR: CUSOLVERError: an invalid value was used as an argument (code 3, CUSOLVER_STATUS_INVALID_VALUE)
Stacktrace:
 [1] throw_api_error(res::CUDA.CUSOLVER.cusolverStatus_t)
   @ CUDA.CUSOLVER ~/.julia/packages/CUDA/oymHm/lib/cusolver/libcusolver.jl:14
 [2] check
   @ ~/.julia/packages/CUDA/oymHm/lib/cusolver/libcusolver.jl:27 [inlined]
 [3] cusolverDnXgesvdp
   @ ~/.julia/packages/GPUToolbox/cZlg7/src/ccalls.jl:33 [inlined]
 [4] (::CUDA.CUSOLVER.var"#1476#1478"{…})(buffer_gpu::CuArray{…}, buffer_cpu::Vector{…})
   @ CUDA.CUSOLVER ~/.julia/packages/CUDA/oymHm/lib/cusolver/dense_generic.jl:326
 [5] with_workspaces(f::CUDA.CUSOLVER.var"#1476#1478"{…}, cache_gpu::CuArray{…}, cache_cpu::Vector{…}, size_gpu::UInt64, size_cpu::UInt64)
   @ CUDA.APIUtils ~/.julia/packages/CUDA/oymHm/lib/utils/call.jl:89
 [6] Xgesvdp!(jobz::Char, econ::Int64, A::CuArray{Float64, 2, CUDA.DeviceMemory})
   @ CUDA.CUSOLVER ~/.julia/packages/CUDA/oymHm/lib/cusolver/dense_generic.jl:325
 [7] top-level scope
   @ REPL[17]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia> S, err = CUDA.CUSOLVER.Xgesvdp!('N', 0, copy(A));
ERROR: CUSOLVERError: an invalid value was used as an argument (code 3, CUSOLVER_STATUS_INVALID_VALUE)
Stacktrace:
 [1] throw_api_error(res::CUDA.CUSOLVER.cusolverStatus_t)
   @ CUDA.CUSOLVER ~/.julia/packages/CUDA/oymHm/lib/cusolver/libcusolver.jl:14
 [2] check
   @ ~/.julia/packages/CUDA/oymHm/lib/cusolver/libcusolver.jl:27 [inlined]
 [3] cusolverDnXgesvdp
   @ ~/.julia/packages/GPUToolbox/cZlg7/src/ccalls.jl:33 [inlined]
 [4] (::CUDA.CUSOLVER.var"#1476#1478"{…})(buffer_gpu::CuArray{…}, buffer_cpu::Vector{…})
   @ CUDA.CUSOLVER ~/.julia/packages/CUDA/oymHm/lib/cusolver/dense_generic.jl:326
 [5] with_workspaces(f::CUDA.CUSOLVER.var"#1476#1478"{…}, cache_gpu::CuArray{…}, cache_cpu::Vector{…}, size_gpu::UInt64, size_cpu::UInt64)
   @ CUDA.APIUtils ~/.julia/packages/CUDA/oymHm/lib/utils/call.jl:89
 [6] Xgesvdp!(jobz::Char, econ::Int64, A::CuArray{Float64, 2, CUDA.DeviceMemory})
   @ CUDA.CUSOLVER ~/.julia/packages/CUDA/oymHm/lib/cusolver/dense_generic.jl:325
 [7] top-level scope
   @ REPL[18]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

</p>
</details>

**Expected behavior**

Get a vector of singular values, and some error measure intrinsic to this method.

**Version info**

Details on CUDA:

```julia-repl
julia> CUDA.versioninfo()
CUDA runtime 12.8, artifact installation
CUDA driver 12.4
NVIDIA driver 550.120.0

CUDA libraries: 
- CUBLAS: 12.8.4
- CURAND: 10.3.9
- CUFFT: 11.3.3
- CUSOLVER: 11.7.3
- CUSPARSE: 12.5.8
- CUPTI: 2025.1.1 (API 26.0.0)
- NVML: 12.0.0+550.120

Julia packages: 
- CUDA: 5.7.3
- CUDA_Driver_jll: 0.12.1+1
- CUDA_Runtime_jll: 0.16.1+0

Toolchain:
- Julia: 1.11.5
- LLVM: 16.0.6

1 device:
  0: NVIDIA TITAN V (sm_70, 11.351 GiB / 12.000 GiB available)
```

Details on Julia:

```julia-repl
julia> versioninfo()
Julia Version 1.11.5
Commit 760b2e5b739 (2025-04-14 06:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake-avx512)
Threads: 1 default, 0 interactive, 1 GC (on 20 virtual cores)
```

### PR DESCRIPTION
**Pull request by amontoison**
close #2761

### CODE REVIEW

File: lib/cusolver/dense_generic.jl [hunk 1]
```diff
@@ -286,29 +286,15 @@ function Xgesvdp!(jobz::Char, econ::Int, A::StridedCuMatrix{T}) where {T <: Blas
...
-    U = if jobz == 'V' && econ == 1
-        CuMatrix{T}(undef, m, p)
-    elseif jobz == 'V' && econ == 0
-        CuMatrix{T}(undef, m, m)
-    elseif jobz == 'N'
-        CU_NULL
-    else
-        throw(ArgumentError("jobz is incorrect. The values accepted are 'V' and 'N'."))
-    end
+    econ == 0 || econ == 1 || throw(ArgumentError("econ is incorrect. The values accepted are 0 and 1."))
```
Comment (maleadt) [inline lib/cusolver/dense_generic.jl]: Shouldn't `econ` be a simple booelan then?

File: lib/cusolver/dense_generic.jl [hunk 2]
```diff
@@ -286,29 +286,15 @@ function Xgesvdp!(jobz::Char, econ::Int, A::StridedCuMatrix{T}) where {T <: Blas
...
+    jobz == 'N' || jobz == 'V' || throw(ArgumentError("jobz is incorrect. The values accepted are 'V' and 'N'."))
```
Comment (maleadt) [inline lib/cusolver/dense_generic.jl]:
```suggestion
    jobz in ('N', 'V') || throw(ArgumentError("jobz is incorrect. The values accepted are 'V' and 'N'."))
```

File: lib/cusolver/dense_generic.jl [hunk 3]
```diff
@@ -286,29 +286,15 @@ function Xgesvdp!(jobz::Char, econ::Int, A::StridedCuMatrix{T}) where {T <: Blas
...
+
+    U = (jobz == 'V' && econ == 0) ? CuMatrix{T}(undef, m, m) : CuMatrix{T}(undef, m, p)
```
Comment (maleadt) [inline lib/cusolver/dense_generic.jl]: I personally prefer simple `if` statements over these IMO hard-to-read ternary expressions.

Wouldn't it also be safer to use the full `(m,p)` version for the `N` case until we hear back from NVIDIA (i.e., only switch based on `econ`)?

File: lib/cusolver/dense_generic.jl (hunk 1 above)
Comment (amontoison) [reply lib/cusolver/dense_generic.jl]: Yes, but I didn't wanted to break the API.
I was not smart when I did this high-level wrapper.

`econ` should be a `int` if we follow the BLAS / LAPACK API but on GPU the API doesn't always match.

Maybe we can remove the restriction on the type and do `econ=Cint(econ)` inside the method to support both int / boolean.

File: lib/cusolver/dense_generic.jl (hunk 3 above)
Comment (amontoison) [reply lib/cusolver/dense_generic.jl]: Yes, it is safer. We don't know how they use `U` and `V` when `jobz = 'N'` so we should not take any risk.

I will update the PR to use some `if` statements.

File: lib/cusolver/dense_generic.jl (hunk 1 above)
Comment (maleadt) [reply lib/cusolver/dense_generic.jl]: > `econ` should be a `int` if we follow the BLAS / LAPACK API

Our wrappers don't exactly follow the BLAS/LAPACK API, otherwise we'd just use the C wrappers, no?

Are you using these wrappers directly? I would have expected an additional layer of abstraction (e.g. `LinearAlgebra.svd!` with an `algorithm` argument), which is easier to promise stability for.

I'd switch to boolean and maybe add a deprecation:
```julia
if !(econ isa Bool)
  Base.depwarn(...)
  econ = (econ != 0)
end
```

Comment (amontoison) [reply lib/cusolver/dense_generic.jl]: For the BLAS/LAPACK API, it depends on whether we are talking about the Fortran one (with all arguments) or the Julia one via `LinearAlgebra.LAPACK`.

The issue with the additional layer of abstraction is that `LinearAlgebra` lacks some high-level interfaces.  
This variant of the SVD is not supported by `LinearAlgebra.svd!`.

That's why I keep a few `LAPACK.*` methods here, we don't have another way to dispatch to them otherwise.  
I use these `LAPACK.*` methods in my packages because they provide the highest-level interface available for the same method on both CPU and GPU.

I don't use `gesvdp!`, which is a quite recent routine in CUDA.
