### PR TITLE
reduce_block fixes.

### LINKED ISSUE #843: Problem in reduce_block?
There might be a small performance error in `reduce_block`. This line
https://github.com/JuliaGPU/CUDA.jl/blob/632f960a332f57aa8b885e39ab6fb7850e6a3bf5/src/mapreduce.jl#L57
allocates spaces for twice the number of threads, but the upper half of that array is never written.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes https://github.com/JuliaGPU/CUDA.jl/issues/843. The loop in `reduce_block` should probably be unrolled, but that's a little complicated with how the occupancy API is used.

### CODE REVIEW

File: src/mapreduce.jl [hunk 1]
```diff
@@ -63,7 +63,12 @@ end
         sync_threads()
         index = 2 * d * (thread-1) + 1
         if index <= threads
-            @inbounds shared[index] = op(shared[index], shared[index+d])
+            other_val = if index + d <= threads
+                shared[index+d]
+            else
+                neutral
+            end
+            @inbounds shared[index] = op(shared[index], other_val)
```
Comment (eschnett) [inline src/mapreduce.jl:71]: This uses `shared[index]` to accumulate values. As shared memory bandwidth is limited, it would be faster to use a register for this, and to only write the last accumulated value into shared memory, i.e. to write only just before the thread becomes inactive.

It would also make sense to eliminate neutral operations, i.e. to pull the `shared[index] = op(shared[index], other_val)` into the if statement.

Comment (maleadt) [reply src/mapreduce.jl:71]: Yeah, the implementation is not very optimized. The neutral value is a pretty messy thing in its entirety, but harder to eliminate from the shuffle-based implementation.

Comment (maleadt) [reply src/mapreduce.jl:71]: One reason I did it this way, IIRC, is that `op(val, neutral)` might change the element type; the output container element type (which we infer from `op`) might be different than the input.
