### PR TITLE
Mark all CUDA ccalls as GC safe

### LINKED ISSUE #2261: Multi-threaded code hanging forever with Julia 1.10
**Describe the bug**

Thanks for your work on this library. Some of the code I wrote with multi-threading and CUDA hangs forever when using *julia-1.10*, it runs correctly with *julia-1.9.4*.

I manually reduced the code to the best of ability using differential testing while still triggering the bug.

**To reproduce**

The program  hangs forever when using 4, 5, 6, 7 and 8 threads (my core count) with julia 1.10. The Minimal Working Example (MWE) for this bug is:

```julia
using CUDA

function main()
    data = rand(ComplexF32, (100, 100, 8, 20, 200))
    cu_result = CUDA.zeros(ComplexF32, (100, 100, 20, 200))

    Threads.@threads for i in axes(data, 5)
        for t in axes(data, 4)
            cu_result[:, :, t, i] .= sum(CuArray(data[:, :, :, t, i]))
        end
    end
end

println("Starting first iteration")
main()
println("First iteration finished")
main()
println("Second iteration finished")
```

The program finishes normally with julia1.9

<details><summary>Manifest.toml</summary>
<p>

```
[[deps.AbstractFFTs]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "d92ad398961a3ed262d8bf04a1a2b8340f915fef"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "1.5.0"

    [deps.AbstractFFTs.extensions]
    AbstractFFTsChainRulesCoreExt = "ChainRulesCore"
    AbstractFFTsTestExt = "Test"

    [deps.AbstractFFTs.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[deps.Adapt]]
deps = ["LinearAlgebra", "Requires"]
git-tree-sha1 = "0fb305e0253fd4e833d486914367a2ee2c2e78d0"
uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
version = "4.0.1"
weakdeps = ["StaticArrays"]

    [deps.Adapt.extensions]
    AdaptStaticArraysExt = "StaticArrays"

[[deps.CUDA]]
deps = ["AbstractFFTs", "Adapt", "BFloat16s", "CEnum", "CUDA_Driver_jll", "CUDA_Runtime_Discovery", "CUDA_Runtime_jll", "Crayons", "DataFrames", "ExprTools", "GPUArrays", "GPUCompiler", "KernelAbstractions", "LLVM", "LLVMLoopInfo", "LazyArtifacts", "Libdl", "LinearAlgebra", "Logging", "NVTX", "Preferences", "PrettyTables", "Printf", "Random", "Random123", "RandomNumbers", "Reexport", "Requires", "SparseArrays", "StaticArrays", "Statistics"]
git-tree-sha1 = "baa8ea7a1ea63316fa3feb454635215773c9c845"
uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
version = "5.2.0"

    [deps.CUDA.extensions]
    ChainRulesCoreExt = "ChainRulesCore"
    SpecialFunctionsExt = "SpecialFunctions"

    [deps.CUDA.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[[deps.CUDA_Driver_jll]]
deps = ["Artifacts", "JLLWrappers", "LazyArtifacts", "Libdl", "Pkg"]
git-tree-sha1 = "d01bfc999768f0a31ed36f5d22a76161fc63079c"
uuid = "4ee394cb-3365-5eb0-8335-949819d2adfc"
version = "0.7.0+1"

[[deps.CUDA_Runtime_Discovery]]
deps = ["Libdl"]
git-tree-sha1 = "2cb12f6b2209f40a4b8967697689a47c50485490"
uuid = "1af6417a-86b4-443c-805f-a4643ffb695f"
version = "0.2.3"

[[deps.CUDA_Runtime_jll]]
deps = ["Artifacts", "CUDA_Driver_jll", "JLLWrappers", "LazyArtifacts", "Libdl", "TOML"]
git-tree-sha1 = "8e25c009d2bf16c2c31a70a6e9e8939f7325cc84"
uuid = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
version = "0.11.1+0"

[[deps.GPUArrays]]
deps = ["Adapt", "GPUArraysCore", "LLVM", "LinearAlgebra", "Printf", "Random", "Reexport", "Serialization", "Statistics"]
git-tree-sha1 = "47e4686ec18a9620850bad110b79966132f14283"
uuid = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
version = "10.0.2"

[[deps.GPUArraysCore]]
deps = ["Adapt"]
git-tree-sha1 = "ec632f177c0d990e64d955ccc1b8c04c485a0950"
uuid = "46192b85-c4d5-4398-a991-12ede77f4527"
version = "0.1.6"

[[deps.GPUCompiler]]
deps = ["ExprTools", "InteractiveUtils", "LLVM", "Libdl", "Logging", "Scratch", "TimerOutputs", "UUIDs"]
git-tree-sha1 = "a846f297ce9d09ccba02ead0cae70690e072a119"
uuid = "61eb1bfa-7361-4325-ad38-22787b887f55"
version = "0.25.0"

[[deps.JuliaNVTXCallbacks_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "af433a10f3942e882d3c671aacb203e006a5808f"
uuid = "9c1d0b0a-7046-5b2e-a33f-ea22f176ac7e"
version = "0.2.1+0"

[[deps.KernelAbstractions]]
deps = ["Adapt", "Atomix", "InteractiveUtils", "LinearAlgebra", "MacroTools", "PrecompileTools", "Requires", "SparseArrays", "StaticArrays", "UUIDs", "UnsafeAtomics", "UnsafeAtomicsLLVM"]
git-tree-sha1 = "4e0cb2f5aad44dcfdc91088e85dee4ecb22c791c"
uuid = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
version = "0.9.16"

    [deps.KernelAbstractions.extensions]
    EnzymeExt = "EnzymeCore"

    [deps.KernelAbstractions.weakdeps]
    EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"

[[deps.LLVM]]
deps = ["CEnum", "LLVMExtra_jll", "Libdl", "Preferences", "Printf", "Requires", "Unicode"]
git-tree-sha1 = "cb4619f7353fc62a1a22ffa3d7ed9791cfb47ad8"
uuid = "929cbde3-209d-540e-8aea-75f648917ca0"
version = "6.4.2"
weakdeps = ["BFloat16s"]

    [deps.LLVM.extensions]
    BFloat16sExt = "BFloat16s"

[[deps.LLVMExtra_jll]]
deps = ["Artifacts", "JLLWrappers", "LazyArtifacts", "Libdl", "TOML"]
git-tree-sha1 = "98eaee04d96d973e79c25d49167668c5c8fb50e2"
uuid = "dad2f222-ce93-54a1-a47d-0025e8a3acab"
version = "0.0.27+1"

[[deps.LLVMLoopInfo]]
git-tree-sha1 = "2e5c102cfc41f48ae4740c7eca7743cc7e7b75ea"
uuid = "8b046642-f1f6-4319-8d3c-209ddc03c586"
version = "1.0.0"

[[deps.LLVMOpenMP_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "d986ce2d884d49126836ea94ed5bfb0f12679713"
uuid = "1d63c593-3942-5779-bab2-d838dc0a180e"
version = "15.0.7+0"

[[deps.NVTX]]
deps = ["Colors", "JuliaNVTXCallbacks_jll", "Libdl", "NVTX_jll"]
git-tree-sha1 = "53046f0483375e3ed78e49190f1154fa0a4083a1"
uuid = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
version = "0.3.4"

[[deps.NVTX_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "ce3269ed42816bf18d500c9f63418d4b0d9f5a3b"
uuid = "e98f9f5b-d649-5603-91fd-7774390e6439"
version = "3.1.0+2"
```

</p>
</details>

**Expected behavior**

I expect the program to finish (and cu_result to contain the correct result).

**Version info**

Details for Julia 1.10

```
Julia Version 1.10.0
Commit 3120989f39 (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, rocketlake)
  Threads: 1 on 16 virtual cores
```

CUDA version with Julia 1.10

```
CUDA runtime 12.3, artifact installation
CUDA driver 12.3
NVIDIA driver 546.12.0

CUDA libraries:
- CUBLAS: 12.3.4
- CURAND: 10.3.4
- CUFFT: 11.0.12
- CUSOLVER: 11.5.4
- CUSPARSE: 12.2.0
- CUPTI: 21.0.0
- NVML: 12.0.0+546.12

Julia packages:
- CUDA: 5.2.0
- CUDA_Driver_jll: 0.7.0+1
- CUDA_Runtime_jll: 0.11.1+0

Toolchain:
- Julia: 1.10.0
- LLVM: 15.0.7

1 device:
  0: NVIDIA RTX A5000 (sm_86, 18.249 GiB / 23.988 GiB available)
```

<details><summary>Version details with Julia 1.9</summary>
<p>

Details of Julia 1.9

```
Julia Version 1.9.4
Commit 8e5136fa29 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, rocketlake)
  Threads: 12 on 16 virtual cores
```

Details on CUDA (Julia 1.9.4):

```
CUDA runtime 12.3, artifact installation
CUDA driver 12.3
NVIDIA driver 546.12.0

CUDA libraries:
- CUBLAS: 12.3.4
- CURAND: 10.3.4
- CUFFT: 11.0.12
- CUSOLVER: 11.5.4
- CUSPARSE: 12.2.0
- CUPTI: 21.0.0
- NVML: 12.0.0+546.12

Julia packages:
- CUDA: 5.2.0
- CUDA_Driver_jll: 0.7.0+1
- CUDA_Runtime_jll: 0.11.1+0

Toolchain:
- Julia: 1.9.4
- LLVM: 14.0.6

Preferences:
- CUDA_Runtime_jll.version: 12.3

1 device:
  0: NVIDIA RTX A5000 (sm_86, 20.694 GiB / 23.988 GiB available)
```
</p>
</details>

**Additional context**

Thanks very much for your help! Please let me know if I can help further with this!

### PR DESCRIPTION
**Pull request by vchuravy**
Using https://docs.julialang.org/en/v1/stdlib/Profile/#Triggered-During-Execution I observed an issue in #2261 where
we acquire a lock in `cuOccupancyMaxPotentialBlockSize` and seemingly get live locked. Other threads
suspend in waiting for GC and no forward progress is being made.

Manually marking `cuOccupancyMaxPotentialBlockSize` as safe to execute GC next to seemingly fixes the issue,
we could add a convenience macro for doing this.

---

Update by @maleadt: I made all ccalls GC safe, made sure callbacks are GC unsafe again.

x-ref https://github.com/JuliaLang/julia/pull/49933

### CODE REVIEW

**Comment by maleadt** [comment]
Pushed a macro version, and used that to mark all `libcuda` ccall's as GC-safe. I'm not confident this is allowed though, or at least not on all Julia versions, when doing a `ccall` that may call back into Julia.

Running the MWE from https://github.com/JuliaGPU/CUDA.jl/issues/2261 repeatedly on 1.8 doesn't seem to crash though.

File: lib/cudadrv/occupancy.jl [hunk 1]
```diff
@@ -36,7 +36,13 @@ end
 # HACK: callback function for `launch_configuration` on platforms without support for
 #       trampolines as used by `@cfunction` (JuliaLang/julia#27174, JuliaLang/julia#32154)
 _shmem_cb = nothing
-_shmem_cint_cb(x::Cint) = Cint(something(_shmem_cb)(x))
+function _shmem_cint_cb(x::Cint)
+    # see @gcsafe_ccall documentation
+    @static if VERSION < v"1.9"
+        GC.safepoint()
```
Comment (vchuravy) [inline lib/cudadrv/occupancy.jl]: Did you mean:

```
state = @ccall jl_gc_unsafe_enter()::Int8
```

and at the end:

```
@ccall jl_gc_unsafe_leave(state::Int8)
```

File: lib/utils/call.jl [hunk 2]
```diff
@@ -165,6 +165,12 @@ render_arg(io, arg::Union{<:Base.RefValue, AbstractArray}) = summary(io, arg)
 
 # TODO: replace with JuliaLang/julia#49933 once merged
 
+# note that this is generally only safe with functions that do not call back into Julia.
+# when callbacks occur, the code should ensure the GC is not running:
+# - on 1.10 and later, everything is fine because of safepoint_on_entry
+# - on 1.9, @cfunction-based callbacks are fine because they transition to gc_unsafe
+# - on 1.8 and earlier, the code should explicitly call GC.safepoint()!
```
Comment (vchuravy) [inline lib/utils/call.jl]: On 1.9+ callbacks from C automatically transition the runtime to GC_unsafe
On 1.8 the code should explicitly transition to GC_unsafe

File: lib/cudadrv/occupancy.jl (hunk 1 above)
Comment (maleadt) [reply lib/cudadrv/occupancy.jl]: I didn't, but I guess I may be misunderstanding. I thought that acquiring a safepoint when GC is active would block / be sufficient of a workaround, also because you mentioned that manual action isn't needed on 1.10 now that we have safepoint_on_entry? i.e., there's no need to transition to GC unsafe here (we aren't invoking the runtime), only to block when the GC is active (which AFAIU you do by trying to acquire a safepoint).

Comment (vchuravy) [reply lib/cudadrv/occupancy.jl]: So the issue is that `cuOccupancyMaxPotentialBlockSize` is now executed with `GC safe` aka "GC allowed to run concurrenty"`. On 1.9+ upon re-entrancy into Julia through the cfunction thunk the Julia code is marked `GC unsafe` aka "GC must wait for safepoint to be reached before running". So everything should be fine. 
A thread is either blocked on the CUDA lock and marked `GC safe`, or a thread is within Julia code an can make forward-progress/hit a safepoint to execute GC.

On 1.8 `cfunction` doesn't handle the GC transition. So we are now marking a thread as `GC safe` and then switch back into Julia code while still being `GC safe`. If a user would insert an `@info` statement into the callback or do anything else interesting we may corrupt a concurrently running GC.

`GC.safepoint()` is part of `jl_gc_unsafe_enter`, but on it's own it is not sufficient. E.g. GC could start immediatly after the safepoint and we would have the same issue.

Comment (vchuravy) [reply lib/cudadrv/occupancy.jl]: I would use:
```
macro gcunsafe(expr)
    if VERSION < v"1.9.0"
        quote
            state = ccall(:jl_gc_unsafe_enter, Int8, ())
            val = $(esc(expr))
            ccall(:jl_gc_unsafe_leave, Cvoid, (Int8,), state)
            val
        end
    else
        return expr
    end
end
```

To wrap the callback functions. I can push that update?

Comment (maleadt) [reply lib/cudadrv/occupancy.jl]: > GC could start immediatly after the safepoint and we would have the same issue.

Ah right, that's the crucial bit I was missing. Thanks!

Comment (maleadt) [reply lib/cudadrv/occupancy.jl]: I'll push the update, as I'll have to rebase this branch on top of the header regenerate PR anyway.

File: lib/utils/call.jl [hunk 3]
```diff
@@ -150,3 +160,102 @@ end
...
+    sig = ex.args[1]
+    @assert Meta.isexpr(sig, :call)
+    body = ex.args[2]
+    @assert Meta.isexpr(body, :block)
+
+    gcunsafe_body = quote
+        gc_state = @ccall(jl_gc_unsafe_enter()::Int8)
+        try
+            $body
+        finally
```
Comment (vchuravy) [inline lib/utils/call.jl:255]: I was debating if the try/finally was necessary and decided that it wasn't. Since we can only catch exceptions in gc_unsafe. cc: @vtjnash for a double check on that.

Comment (vtjnash) [reply lib/utils/call.jl:255]: The `try` setup seems a bit risky to be present inside `jl_gc_safe_enter`, a `catch/finally` already implicitly reset the gc state upon leave (normal or error)

Comment (maleadt) [reply lib/utils/call.jl:255]: The `try` happens after `jl_gc_unsafe_enter`?

Comment (vtjnash) [reply lib/utils/call.jl:255]: Then I don't see how this is reachable, since cfunction already had to do an unsafe-enter to be able to dispatch into the runtime

Comment (vtjnash) [reply lib/utils/call.jl:255]: Oh, I see this is for v1.8. That seems okay. I am surprised that is still supported here
